### ISSUE TITLE
Pod not up to date

### ISSUE THREAD

**Issue by baoluo** [contentful/contentful.swift#1]
Hello Contentful,

Your pod is not up to date, please create a new release that I can tag in my pod file !

Also, the pod is nowhere to find if I don't add :github '', :tag '0.1.0'

**Comment by baoluo** [comment]
I don't want to be rude or anything, but you're expecting us to pay for full access, but your API is almost unusable as it. Please tell me if the OBJC one works better, even under Swift.

Thanks

**Comment by neonichu** [comment]
Sorry, but this project is still experimental. For the time being, you are better off using the ObjC SDK, have a look at <https://github.com/contentful-labs/swiftful> for a simple example on using that from Swift.

**Comment by neonichu** [comment]
Shipped to trunk as version 0.2.0
