### ISSUE TITLE
Mapping result to struct 

### ISSUE THREAD

**Issue by mortocks** [contentful/contentful.swift#10]
Any chance of a simple example of mapping result to a struct (or point to documentation example)? Thanks

````

import Decodable

struct Cat {
    let name: String
}


extension Cat:Decodable {
    static func decode(j: AnyObject) throws -> Cat {
        return try Cat(
            name: j => "nested" => "name",
        )
    }
}

let client = Client(spaceIdentifier: "cfexampleapi", accessToken: "b4c0n73n7fu1")
client.fetchEntry("nyancat") { (result) in
    switch result {
        case let .Success(entry):
            print(entry)

           // Now what? Map entry to Cat, using decode perhaps?

        case .Error(_):
            print("Error!")
    }
}

**Comment by neonichu** [comment]
If you want to use your own structs, I would encourage you to check out <https://github.com/contentful-labs/contentful-generator.swift>, which will auto-generate mapping code directly from your data model on Contentful.

For your example, you'd access the `name` field using something like this:

```swift
let cat = Cat(name: (entry.fields["name"] as? String) ?? "")

**Comment by neonichu** [comment]
I'm assuming the question has been answered and this can be closed.
