### ISSUE TITLE
Please Update Your Documentation (3 Months of Inconsistencies)

### ISSUE THREAD

**Issue by AntonTheDev** [contentful/contentful.swift#105]
> - contentful.swift version number:  0.8.0
> - Xcode version number: 8.3+
> - Target operating system(s) and version number(s)
    - [x] iOS:  Any Supported Version 
    - [x] tvOS:  Any Supported Version 
    - [x] watchOS:  Any Supported Version
    - [x] macOS: Any Supported Version
> - Package manager:
    - [x] Carthage
    - [x] Cocoapods

Please update your Documentation for Swift! This is killing me, not only are we being forced to adapt mapping frameworks that aren't part of the current workflow, there are no clear examples documented as part of your framework on how to adapt your Modellable protocol. Since the library does not just return a JSON response, nor provide access to included entries, this is taking way longer than it should from a development perspective.

**Comment by loudmouth** [comment]
Hi @AntonTheDev , sorry for the inconsistencies in documentation.

Over the past few months, I've been working frantically to take an incomplete SDK to a stable and feature complete position. The SDK is quite stable now and a `1.0.0-beta1` version should be coming very soon.

However, rapid development has unfortunately had the side-effect of invalidating the documentation at www.contentful.com/developers. I will work on updating it today.

That being said, I have a few additional points which you may find useful:
- The `Modellable` protocol is in Beta as is clearly listed in the README. Despite the fact that it "works", I do not consider it stable and the API is still subject to change.
- Given that the SDK has 86% test coverage, there is often a good chance that you can find example usage [somewhere in the tests](https://github.com/contentful/contentful.swift/tree/master/Sources).
> "Since the library does not just return a JSON response"...
  - The SDK automatically resolves links for you so you do not have to worry about includes. Of course you can specify the level of includes when doing a query (as in the code snippet below) but the actual links/relationships _will_ be resolved by the SDK if they were included in the response. 
This the benefit of the SDK: there is no need to worry about the JSON format Contentful uses  and the complexities that arise from link resolution. Forwarding just a JSON response would, in my opinion, render the SDK useless.

```swift
client.fetchEntries(matching: ["include" : 3]) { (result: Result<ArrayResponse<Entry>> in
  // your result will have all fields that represent links pointing to actualized objects, be it an `Asset`, `[Asset]`, `Entry`, or `[Entry]`
}
```

Lastly:

- ObjectMapper is necessary dependency at the moment but when the migration to Swift 4 occurs, it will be pruned from the SDK.

**Comment by AntonTheDev** [comment]
I was wondering is there a way to stop the recursive loop. I am attempting at using the EntryModellable protocol, I have an Entry that references a parent which holds a reference to array of the Entries. But it appears that the link depth is set to 20, and it spins through forever trying to resolve all the instances, until I receive an EXEC_BAD_ACCESS. Are there any work arounds for this?

**Comment by loudmouth** [comment]
Hi @AntonTheDev unfortunately there is no workaround at the moment. 

This link resolution issue is one of the main reasons I have marked the `Modellable` protocols as beta—it is not stable yet. I have some ideas on how to alleviate this issue other priorities have kept me from working on it. I will do my best to find improve the `Modellable` system as soon as I can, but I cannot guarantee a fix this week.

I would recommend using the other methods that the SDK provides for the time being and I will continue to provide updates about the progress of the `Modellable` protocols in the meantime.

**Comment by AntonTheDev** [comment]
Good times man, I'm gonna close this issue. I think I have a solution to the loop of death :P Might help out with the documentation too, if you guys are accepting pull requests?

**Comment by loudmouth** [comment]
Hey @AntonTheDev ,

Pull requests are definitely welcome. I'd love to know the particulars of what you are looking to merge and how. Would you be willing to detail what changes to the documentation you'd like to see? I updated the [API reference documentation for contentful.swift](https://contentful.github.io/contentful.swift/) yesterday, but was unable to get to updating the resources at contentful.com/developers.

Regarding the issue with `Modellable` and link resolution/depth, I also have a fix in mind which I am working on which I have started working on this morning. My schedule is packed with meetings today so it is likely not much progress will be made, but maybe we can take the conversation to a new issue to scope the fix you were thinking.

**Comment by loudmouth** [comment]
Hey @AntonTheDev 
I'm definitely curious to hear about the solution you have in mind for the `Modellable`/ link depth issue.

Would you be willing to open a new github issue with your proposed solution and we can flesh out a spec for a pull request together?

I'd be happy to do the work of implementing it :-)
