### ISSUE TITLE
Modellable Child <-> Parent Relationship Creates Endless Loop

### ISSUE THREAD

**Issue by AntonTheDev** [contentful/contentful.swift#107]
> - contentful.swift version number: 0.8.0
> - Xcode version number: 9.0 +
> - Target operating system(s) and version number(s)
    - [X] iOS: 
    - [X] tvOS: 
    - [X] watchOS:
    - [X] macOS:
> - Package manager:
    - [X] Carthage
    - [X] Cocoapods

It appears when I have a parent that contains an array of children, and the children reference the parent, during the mapping process there is an infinite loop that causes the framework to crash. The child will try to map the parent, then the parent re-attempts at mapping the child which then causes the child try to map the parent again, and so on..... until the crash.

In my code I am currently mapping my data manually until this is fixed, but hopefully it inspires a solution on your side to fix it.  For this example imagine a Series, which contains Seasons, which contains Videos. I may need each entity at some point to reference it's parent. Thus the Video would need to tell me which season it is part of, and each season may need to tell me which series it is part of. 

```
final class Series {
    static let contentTypeId: String = "series"
    var seasons : [Season]?

    init?(entry: Entry) {
        ...
        if let seasonLinks = entry.fields["seasons"] as? [Link] {
            var seasonArray = [Season]()
            
            for link in seasonLinks {
                switch link {
                case .entry(let seasonEntry):
                    if let season = Season(entry: seasonEntry, parentSeries : self) {
                        seasonArray.append(season)
                    }
                default:
                    continue
                }
            }
            
            seasons = seasonArray
        }   
    }
}

final class Season {
    static let contentTypeId: String = "season"
    var parentSeason : Series?
   
    init?(entry: Entry, parentSeries : Series? = nil) {
       ...
        if parentSeries != nil {
            self.parentSeries = parentSeries
        } else {
            // parse the parent
        }
    }
}

final class Video  {
    static let contentTypeId: String = "video"
    var parentSeason : Season?
   
    init?(entry: Entry, parentSeason : Season? = nil) {
        ...
        if parentSeries != nil {
            self.parentSeries = parentSeries
        } else {
            // parse the parent
        }
    }
}

```

If there is a way to identify the parent relationship, and you can tell the child "Hey, I'm your elder don't map me", the child can mapping it and stop the infinite loop. hopefully this inspires some creativity on your part to identify these relationships during mapping :)

**Comment by loudmouth** [comment]
Hey @AntonTheDev I really appreciate you proposing your solution here. This has not been the simplest problem to solve, and I was really hoping to unify the `Modellable` protocols with the `Persistable` protocols contained in [contentful-persistence.swift](https://github.com/contentful/contentful-persistence.swift). In fact, my attempts to unify these protocols are the reason progress here has been slow. Now, I have come to the conclusion that `NSManagedObject` subclasses (which _must_ be initialized with an `NSManagedObjectContext` can't be treated the same as regular model classes to be used in-memory only and I'm moving forward with a solution that works.

## The fix
It's important that there are no duplicate instances of the same entry floating around in memory and that the object graph complete with a single unique entity for each Contentful `Entry` As such, deserializing an entry to a `Modellable` type will require initialization of all _regular_ (non-relationship) properties in one step using:

```
init(entry: Entry)
```

Next, the SDK will cache any relationship representations with a unique key and then when the protocol method

```
func populateLinks(from cache: [FieldName: Any])
```

is called by the system, the cache will contain deserialized types of the consumers definition also conforming to `Modellable` or possibly an `Asset`. These `Modellable` or `Asset` instances will already have been deserialized in the first step and then and cached by the system for use here.

An implementation for a model class will look like the following example:

```
final class Cat: EntryModellable {

    static let contentTypeId: String = "cat"

    let id: String
    let localeCode: String
    let color: String?
    let name: String?
    let lives: Int?
    let likes: [String]?

    // Relationship fields.
    var bestFriend: Cat?

    init(entry: Entry) {
        self.id         = entry.id
        self.localeCode = entry.localeCode

        self.name       = entry.fields["name"] as? String
        self.color      = entry.fields["color"] as? String
        self.likes      = entry.fields["likes"] as? [String]
        self.lives      = entry.fields["lives"] as? Int
    }

    func populateLinks(from cache: [FieldName: Any]) {
        self.bestFriend = cache["bestFriend"] as? Cat
    }
}
```

I need to write one or two more tests and finish the documentation for these methods, but the code should be working and is available in #108 

Thanks for your patience.

**Comment by AntonTheDev** [comment]
Although I see where your solution is headed, and it is a good one if I'm starting a project from scratch, yet I'd highly recommend a stripped down JSON response like most frameworks provide. I truly believe that parsing and persistence should not forced upon the implementor as this could have huge ramifications on the implementation effort on a team that may not starting from scratch and/or building their applications against a very mature MVVM architecture.

From the experience, I could have had my whole model simply remapped in about 2 hours from a simple JSON, yet I spent three days learning a new mapping approach, building a brand new model, and accounting for complex relationships occurring from the recursive loop. 

Also, the fact that core-data is not supported for long term storage on an Apple-TV, building out a whole persistence layer and making it interdependent with the ingestion layer is putting a lot of focus optional functionality.

**Comment by loudmouth** [comment]
@AntonTheDev thanks so much for the feedback.

I hear your argument that integrating this mapping approach in applications that already has an established model may be difficult. And I have a few further questions to understand how best to proceed if you don't mind:

1. When you mention returning a stripped down JSON response, what exactly are you asking for? A reformed JSON object with the link properties resolved to nested objects rather than link metadata? Is there any issue with returning `Entry` and `Asset` types like all other methods on `Client` return asynchronously? All other Contentful delivery SDK's return `Entry`s and `Asset`s. 

2. The fix being proposed does fix the current issue which utilizes this mapping framework that has already been published; shouldn't this mapping framework work as is, despite potential design flaws? In other words, is the PR being proposed worthy of a merge? If not, should the entire `Modellable` concept be thrown away all together? I'm open to suggestions.

3. If you found this so painful to begin with, why did you choose to use these methods at all? Was it the functionality provided by the `Query` types (for instance? What is the thing that should be iterated on to make for a better user experience?

Sorry to bombard with so many questions, but as a consumer of the SDK, your input is valuable in moving forward with design decisions, which are otherwise, left to me in isolation.

**Comment by AntonTheDev** [comment]
No worries at all man! I like to contribute thoughts, love a constructive conversation, and I believe the best solutions come out of it. In response to your points:

1. I believe that you guys have a very good model for using an object graph. From experience, when considering an object graph, and this is not the first time when I've worked with one, the biggest pitfall is to avoid creating a recursive loop. An object graph is great for creating a RESTful API, and allows for the ability to drill down a stack of data with ease, especially when you drill down one level at a time using an identifier (aka Link) in contentful.  

Let's consider the Series <-> Seasons <-> Episodes. All is perfect if the intent is to couple model to with the UI, and return a Series object that has fields representing the season count, the episode count, the premier dates of the the latest episodes, etc. If those values existed, I could use those for display purposes on the landing page for the Series instance, but I would need to ensure that the Series object is always updated whenever I add a new season, or a new episode, etc. 

This can become cumbersome, and it indirectly couples my UI to the values on the Series instance, without allowing me the flexibility to introspect a couple levels deeper. Since there isn't a serializer to generate these values in the response without some backend logic when querying contentful, we need to go a few levels deeper in fetching the response. (Possible consider linking some kind of dynamically generated fields with values in the response, with some kind of customizable transforming ability in the CMS)

Now getting back to the JSON response. If I want to view a whole series at once, Series <-> Seasons <-> Episodes, I would love to drill down 3 levels only an get the Series as an object, with all it's children, and sub-children. As in our case, there is a need to fetch multiple levels of data to be accessed at once, and there is a dependency on a parent <-> child relationship that cannot be avoided. I've run into this issue before, and in another video application for which we were using CodeData to store the content, we had run into the same issue, having to create a variable synchronizer. The problem was, if we got too much data we would hit a recursive loop, if we didn't get enough data, data we had stored would be overwritten with empty values, causing another headache. 

Since that project about 7 years ago, whenever there is no actual need to modify the data on disk, or calculate any complex values in a big data set, I have resorted to simply serializing a JSON response to disk straight up, always naming the file as the url name without after stripping out special characters. 

So in a way, you guys do return everything in JSON, technically the fields array as part of the Linked Entry, but unfortunately the fields do not contain the id for the entry itself, hence I made this to add it in there...

https://gist.github.com/AntonTheDev/e498b82917a9a5b81888be6ab08abb8a

JSON is industry accepted, most people have many solutions as to how to approach parsing the JSON, also as per example above how they persist the response, and we should not be obligated to a mapping solution. In the end for speed and consistency sake, keeping one mapping framework in the application versus implementing two solutions per integrated system leads to code cleanliness, and keeps the architecture consistent. 


2. I believe that the modellable concept is great! If you start a project from scratch, but in our case we didn't need the persistence layer, nor did we need to remap everything using a ObjectMapper, which by the ways is great if there was a quick example of how to parse Linked Entries. I should of been able to just remap my current model and move forward. Thank goodness for a good MVVM implementation, because it made integrating the model provided by the framework manageable, since the View Model drives the UI, and completely hide the model from the UI, it was was a seamless yet manual transition. But I cannot assume that everyone is using MVVM, nor could I say that I've seen it implemented with pure perfection, which I'm still thriving to achieve.

I would stick with the Modellable approach, but I would checkout Spotify's framework to see an how they have two types of calls per end point, one that returns model objects, and one that returns a JSON response if you choose another route.  I believe that our developers on another project literally by passed the whole javascript framework, and straight up approached the data as the original JSON response to create their own solution. There is a lot returned, and if you don't truly have a grasp as to how contentful returns the data, it does take a few brain cells to run through it and decipher the responses.

3. You are exactly correct about this, that the query object is of most importance in the choice to use this framework, but not the only reason. the specifics lie behind the delivery time frame of our project, the long API documentation, and implementing a networking layer with end point configuration after tracking down the endpoint we needed to get the data we wanted to use.

I hope this clarifies some of my thoughts, and sparks some new ones  :)
- Anton

**Comment by loudmouth** [comment]
Awesome feedback!

I have a few thoughts moving forward: 

1. The PR I have posted should indeed be merged as it does fix the recursive loop issue originally described above. It ensures an object graph without duplicates and with a complete relationship mapping (assuming all relevant relationships were returned in the JSON response). That pull request should effectively close this issue.

2. I've just opened an [additional issue] #109 as a feature request to flesh out this concept of re-working the JSON in place so that fully JSON representations of linked objects are nested in the `fields` dictionary as opposed to the "normalized" response that the API returns. Maybe we can continue spec'ing out this feature there so we have something that further facilitates integration with apps that already have mature data models (and mapping code).

Btw, is [this](https://github.com/spotify/ios-sdk) the Spotify framework you mentioned?

**Comment by AntonTheDev** [comment]
It's a good day man!  Thats definitely the framework :)

Is you checkout the [headers](https://github.com/spotify/ios-sdk/blob/master/SpotifyMetadata.framework/Headers/SPTListPage.h) got a paged request here.

You will notice that they have a request generating method in there a similar method to retrieve modeled objects. The different though between contentful and spotify is that they run of a restful API vs a headless CMS. I believe finding a way to massage the data to a familiar response as you are doing is going to be very very powerful in the future :)

Glad to hear I could help spark a some ideas, and looking forward to your PR :)

**Comment by popei69** [comment]
Hi there,

First, thanks for the help and all thoses detailed, I'm facing a similar and still try to work around it. 

I based part of the code with the example of relationship given with `populateLinks`. However it seems not working for a `ONE TO MANY` relation (if the Cat as more than one `bestfriend`). Is there a workaround for this one? 

Thanks

**Comment by loudmouth** [comment]
@popei69 which version of the SDK are you using?

Is the issue for you that you are running into a endless loop for relationship resolving? I would be quite surprised if this was happening in versions >= 0.9.0 of the SDK as the entire scheme for resolving relationships has changed. Maybe you are reporting a different bug: that the relationship simply isn't resolved when it's one-to-many?

**Comment by popei69** [comment]
@loudmouth I'm currently using 0.9.1. Sorry for the confusion, I don't have the endless loop issue. My challenge is about creating a ONE TO MANY relationship populated via the `populateLinks` method. Let me know if I should create a separated ticket for that, I eventually find a work around by integrating Array.Type in `relationshipNames` method.

**Comment by loudmouth** [comment]
@popei69 another issue would be awesome :-)

**Comment by loudmouth** [comment]
@popei69 when you open a new issue, could you also paste some example code?
