### ISSUE TITLE
Carthage fails to build in Swift 3

### ISSUE THREAD

**Issue by foreldet** [contentful/contentful.swift#11]
I've tried to use `carthage update --platform iOS` with Swift 3 branch, but it fails to build by referencing CocoaPods.

```
*** Building scheme "Contentful" in Contentful.xcworkspace
** BUILD FAILED **


The following build commands failed:
    PhaseScriptExecution Check\ Pods\ Manifest.lock /Users/****/Library/Developer/Xcode/DerivedData/Contentful-auzeobpdvgvojlduvsjargjwtodp/Build/Intermediates/Contentful.build/Release-iphoneos/Contentful.build/Script-40E859107A3926159C69D196.sh
(1 failure)
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/****/Desktop/****/Carthage/Checkouts/contentful.swift/Contentful.xcworkspace -scheme Contentful -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

```

In my Cartfile I have this:

`github "contentful/contentful.swift" "swift-3.0"`

**Comment by neonichu** [comment]
The Swift 3 branch isn't quite up to date and doesn't support Carthage at the moment

**Comment by foreldet** [comment]
Is there an ETA? Otherwise I'll try to integrate it and send you a pull request

**Comment by neonichu** [comment]
I don't have an ETA right now.

**Comment by baqtiste** [comment]
hey @foreldet 
Did you succeed to build with Carthage and swift 3 ?

**Comment by loudmouth** [comment]
Hi @foreldet and @baqtiste, there is a pre-release, `v0.3.0` available currently for available via Carthage and CocoaPods as well. 

[contentful-persistence.swift](https://github.com/contentful/contentful-persistence.swift) is unfortunately not quite ready.
