### ISSUE TITLE
Expose ContentModel init

### ISSUE THREAD

**Issue by popei69** [contentful/contentful.swift#116]
> - contentful.swift version number: 0.9.1
> - Xcode version number: 8.3.3
> - Target operating system(s) and version number(s)
    - [x] iOS:  Any Supported Version
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [ ] Carthage
    - [x] Cocoapods

While trying to use `client.fetchMappedEntries` I realised it's based on `ContentModel`object defined in `Client`.

However, ContentModel initialiser is inaccessible due to internal protection level. I can't create a new ContentModel for my client, and so, can't map entries. To workaround, I exposed ContentModel init as public but it might be something useful to implement for others except if I missed something else?

Thanks

**Comment by loudmouth** [comment]
Good catch @popei69 . Should have this fixed very soon.
