### ISSUE TITLE
Forcing me to unlock the pod file.

### ISSUE THREAD

**Issue by spynet** [contentful/contentful.swift#12]
Right now my team is working on swift 3 migration , while i migrate the existing pod to this path : 

> pod 'Contentful', :git => 'https://github.com/contentful/contentful.swift', :branch => 'swift-3.0'

It Force me to do unlock the podlock file

how to fix this issue or suggest any solution

**Comment by spynet** [comment]
I Feel that you have not migrated the swift 3.0 entirely ,
Please do as soon as possible or suggest the alternate solution.

**Comment by mariobodemann** [comment]
Hey,

we are working on a swift 3 migration, sadly we are not yet production ready, since our dependent libraries are also not yet swift 3 compatible. If you want to take a look at the branch, please check it out here: https://github.com/contentful/contentful.swift/tree/swift-3.0

Greetings, Mario

**Comment by spynet** [comment]
Hi ,
Thanks for the reply,
May i know the ETA (Expected Time) ?

Thanks in advance

**Comment by mariobodemann** [comment]
Hey,

sadly we do not have an ETA. But rest assured we are working on it, and according to our current workload we will prioritise it.
