### ISSUE TITLE
Swift example project

### ISSUE THREAD

**Issue by andrejbroncek** [contentful/contentful.swift#123]
> - contentful.swift version number: 0.9.2
> - Xcode version number: 9.0 beta 6
> - Target operating system(s) and version number(s)
    - [x] iOS: 10
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [ ] Carthage
    - [x] Cocoapods

Hello guys,

I am having problems setting up even the simplest of things in my project using your SDK. I tried looking into the tests, documentation, tutorials but they are way too generic. 

What I need is extremely simple, yet I am struggling to achieve it. I basically just want to fetch posts from the Contentful. Lets say I have model named "Post" which reflects the post, posts can be put into categories reflected by another model called "Category". 

 What I tried to fetch the posts is this:

 ```
let query = Query(where: "content_type", .equals("post"))

client.fetchEntries(with: query) { result in
            switch result {
            case .success(let entriesArrayResponse):
                 print(entriesArrayResponse.items)
            case .error(let error):
                print("error.localizedDescription")
            }
        }
```

yet all I get back is error saying - Contentful.ContentfulError error 1.

I tried going through queries for contentTypes, tried fetching all entries, but I am not able to find the right content_type to fetch just the posts, nothing else. 

I am really struggling, it feels like using just a raw JSON response would have been quicker and easier, I cannot get anything to work with this SDK :/ Are you guys planning on creating some sample projects which would use all the SDK features and provide some test user access to the Contentful space they would be using? So we get to see a real use of the Contentful iOS SDK.

**Comment by loudmouth** [comment]
Hi @andrejbroncek , we are working on some new example applications at the moment so hang tight.

In the meantime, the SDK's reference documentation is quite thourough in my opinion. You should be able to browse it directly in XCode, but if you have specific requests for improvements, they are more than welcome. It looks like you are receiving a `ContentfulError` object back from the SDK, which means that the API itself has returned an error. You can see that `ContentfulError` has a `message` property which will forward you the human readable error message that Contentful's Content Delivery API has returned. My best guess is that you have an incorrect access token.

I think maybe as a feature request for the SDK, i could bridge the `localizedDescription` field of the SDK to forward the `message` when the error is a `ContentfulError`

**Comment by loudmouth** [comment]
@andrejbroncek were you able to figure out what the error message being forwarded from the API was?

**Comment by andrejbroncek** [comment]
@loudmouth yes, after reviewing the error message, it was caused by bad `"content_type"` reference. I still feel like I will rather use the API directly without the provided SDK for the sake of simplicity, but thanks for helping me out :)

**Comment by loudmouth** [comment]
@andrejbroncek I'm sorry that you feel the SDK is so painful to use for you. I think the one concrete takeaway is that the `localizedDescription` method on `NSError` can be bridged to all of the SDK's various error types.

Otherwise, I'd appreciate some concrete feedback from your end if you have any. So far, I don't don't have any perspective on how SDK usage is cumbersome in your eyes—only that the error's `localizedDescription` did not provide helpful information.

**Comment by loudmouth** [comment]
Also, as the example app is being specced out currently and hasn't started development, one trick with open source projects is to look into the Tests as the tests test usage. You can see in the [EntryTests](https://github.com/contentful/contentful.swift/blob/master/Tests/ContentfulTests/EntryTests.swift) file how and the [QueryTests](https://github.com/contentful/contentful.swift/blob/master/Tests/ContentfulTests/QueryTests.swift) file how to do many of the relevant operations you're attempting to do

**Comment by loudmouth** [comment]
At long last there is now an example project at https://github.com/contentful/the-example-app.swift !

It uses in-memory object models (as opposed to using CoreData).
