### ISSUE TITLE
CocoaPods Swift 3.0 version

### ISSUE THREAD

**Issue by 6franek** [contentful/contentful.swift#13]
Are there any plans to release Swift 3.0 on CocoaPods? If yes, what is the ETA?

**Comment by mariobodemann** [comment]
Hey,

we are working on a branch https://github.com/contentful/contentful.swift/tree/swift-3.0, taking care of the swift migration, sadly I cannot give you an ETA ...

**Comment by loudmouth** [comment]
Hi @6franek, there is a pre-release available currently. `v0.3.0` which can be installed via CocoaPods or Carthage.

[contentful-persistence.swift](https://github.com/contentful/contentful-persistence.swift) is unfortunately not quite ready.
