### ISSUE TITLE
EntryModellable doesn't handle ImplicitOptionals

### ISSUE THREAD

**Issue by bennichols** [contentful/contentful.swift#133]
> - contentful.swift version number: 0.9.3
> - Xcode version number: 9.0
> - Target operating system(s) and version number(s)
    - [x ] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [x ] Carthage
    - [ ] Cocoapods

When I have properties that are required in the CMS, I'd like them to be implicit optionals (end in !) so that I don't have to worry about unwrapping them. Currently anything that is an implicit optional is ignored by then `relationshipNames` function.

**Comment by loudmouth** [comment]
Thanks for the reports @bennichols 

I'm a bit busy this week but will try to get a fix out as soon as i have capacity.

**Comment by loudmouth** [comment]
A quick note, as I mentioned in #132 , a new system will be rolled out for decoding entries. Since it will be leveraging the `Decodable` protocol, you will be able to define your classes however you like. Hang tight in the meantime, and thanks for your patience.
