### ISSUE TITLE
'contentTypeInfo' is inaccessible due to 'private' protection level in 'Sys.swift'

### ISSUE THREAD

**Issue by tadasz** [contentful/contentful.swift#135]
> - contentful.swift version number: 0.10.1
> - Xcode version number: 9.0
> - Target operating system(s) and version number(s)
    - [x] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [ ] Carthage
    - [x] Cocoapods

When trying to compile the pod i get the error that 'contentTypeInfo' has a private protection level and cannot be accessed in the initialiser.

File: Sys.swift
Line number: 52

**Comment by loudmouth** [comment]
Hmm...very strange that this issue is only happening on installation for you as it works fine on my machine and on travis. Either way, it should be changed to `fileprivate` i believe.

**Comment by loudmouth** [comment]
@tadasz can you check the branch  `hotfix/protection-level` using cocoapods and see if the pod compiles?

**Comment by GregIngelmo** [comment]
Just changed locally it to fileprivate and it compiled.

**Comment by GregIngelmo** [comment]
It compiles w/ Hotfix branch, added this to Podfile. 
```ruby
pod 'Contentful', :git => 'https://github.com/contentful/contentful.swift.git', :branch => 'hotfix/protection-level'
```

**Comment by loudmouth** [comment]
awesome. thanks @GregIngelmo
