### ISSUE TITLE
How to fetch entries with all locales and access localized data

### ISSUE THREAD

**Issue by tadasz** [contentful/contentful.swift#137]
> - contentful.swift version number: 0.10.2
> - Xcode version number: 9.0
> - Target operating system(s) and version number(s)
    - [x] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [ ] Carthage
    - [x] Cocoapods

I'm having issues accessing localised entries. That's how i tried to do it now:
1. I fetch the entry with 'fetchEntries' function and add "locale": "*" to query. It does work, i can see that that private var 'includes' has localizableFields with both locales.
2. On response object i iterate on 'items' and call setLocale() function
3. When trying to access fields on Entries from items array, that i called setLocale function, the content is still has default locale.

Do I do something wrong or there is a bug?

Thanks!

**Comment by loudmouth** [comment]
Hey @tadasz Not sure. I'll take a look into this tomorrow.

**Comment by loudmouth** [comment]
@tadasz there are indeed tests indicating showing that the `setLocale(withCode:)` method behaves as expected. 

Are you sure the code you are passing in is valid?
Can you share some code of how you are trying to access the field?

**Comment by tadasz** [comment]
This is what i do:



`client.fetchEntries(matching: ["content_type": "rejection", "include": "2", "locale": "*"]) { result in 
switch result {
                case let .success(entry):
                    
//I create my own dictionary with values from response default response is in "en-US" locale, everything is fine
                    var rejections = [Rejection]()
                    let transformedArray = entry.items.map { self.entryToDictionary(entry: $0) }
                    rejections = transformedArray.flatMap { Rejection(with: $0) }
                    var rejectionsDict = [String: Rejection]()                                        
                    rejections.forEach {
                        rejectionsDict[$0.trickId] = $0
                    }
//
for e in entry.items {
                            let didSetLocale = e.setLocale(withCode: "lt")
                            let localizedEntry = self.entryToDictionary(entry: e)
                            //here i get "en-US" values not "lt"
                           
                        }
}`

//entryToDictionary
`private func entryToDictionary(entry: Entry) -> [String: Any] {
        var dictionary = [String: Any]()
        
        for field in entry.fields {
            let key = field.key
            
            if let value = field.value as? Int {
                dictionary[key] = value
            } else if let value = field.value as? String {
                dictionary[key] = value
            } else if let value = field.value as? Link {
                dictionary[key] = linkToAny(value)
            } else if let entryArray = field.value as? [Link] {
                let dict = entryArray.flatMap { linkToAny($0) }
                dictionary[key] = dict
            } else {
                dictionary[key] = field.value
            }
        }
        
        return dictionary
    }`

**Comment by loudmouth** [comment]
Hi @tadasz sorry for the delayed response. Are you sure that your entries have values in the locale `"lt"`? One way to figure this out is by hitting `cdn.contentful.com/spaces/<YOUR_SPACE_ID>/entries?locale=lt&access_token=<YOUR_ACCCESS_TOKEN>` in your browser.

The reason I ask is because the SDK does the same thing that the API does if the `locale=*` is specified: The SDK will walk the fallback chain until a value is found. So, if `en-US` is specified as the fallback locale for the `lt` locale, and no value at a field is present in the locale `lt`, you will get the english value.

You can also try hitting ``cdn.contentful.com/spaces/<YOUR_SPACE_ID>/entries?locale=*&access_token=<YOUR_ACCCESS_TOKEN>` in your browser to confirm if you see a value for `lt` for all your entries.

If you can confirm that there _are_ values for your field in the `lt` locale, then I will have to consider this ticket a bug. If you'd like the contentful support team to look at the data in your space to help confirm the above, please reach out via http://support.contentful.com/

**Comment by tadasz** [comment]
Hi @loudmouth I can confirm that I can see both fields when i use * as locale and see 'lt' values when use 'lt' as locale

<img width="834" alt="screen shot 2017-10-17 at 15 17 03" src="https://user-images.githubusercontent.com/298452/31666986-6256616e-b34e-11e7-85b2-8d278d007c92.png">

**Comment by loudmouth** [comment]
@tadasz sorry for the back and forth. Can you do me one more favor? Can you stop in the deubber at the line right after you set the locale and `po e.currentlySelectedLocale`?
```
let didSetLocale = e.setLocale(withCode: "lt)
let localizedEntry = self.entryToDictionary(entry: e)
```

The reason I ask is that I'm curious if somehow the locale code was somehow not cached by the SDK...

**Comment by loudmouth** [comment]
Also, why are you doing entryToDictionary? The `fields` dictionary is already a `[String: Any]`. I cannot see what your transformation actually accomplishes except that it filters out arrays of strings and casts `Link` to `Any`

**Comment by tadasz** [comment]
Ok i can see that this entryToDictionary is messing with my data, let me remove it and rewrite it properly as it was writen by someone who is not with us anymore. I will let you know

**Comment by loudmouth** [comment]
@tadasz, to confirm then: when trying to access localized content _without_ first transforming it via the `entriesToDictionary` method, everything works?

**Comment by tadasz** [comment]
Hmm, no.

So I print locale after setting it:
(lldb) po entry.currentlySelectedLocale.code
"lt"
But once I print whats inside
```
(lldb) po (entry.fields["reason"] as! [Contentful.Link])[0].entry?.fields
▿ Optional<Dictionary<String, Any>>
  ▿ some : 2 elements
    ▿ 0 : 2 elements
      - key : "id"
      - value : 7
    ▿ 1 : 2 elements
      - key : "text"
      - value : "Cannot see the dog, try again!"
```
text is in en locale. But if i try to debug the entry variable i can see that backend returned 'lt' value

![screen shot 2017-10-17 at 19 05 11](https://user-images.githubusercontent.com/298452/31678370-44042e4c-b36e-11e7-8c26-8916a825e8fa.png)

**Comment by loudmouth** [comment]
I'm glad we're making progress.

 The linked entry itself is another instance of `Entry` that also resides in the `items` array. So, as you're accessing a linked entry, you also need to call `setLocale` on that entry as you are not guaranteed that that entry has already been accessed in your `for` loop. 

```
let links = entry.fields["reason"] as! [Contentful.Link]
let firstLinkedEntry = links.first!.entry
firstLinkedEntry.setLocale(withCode: "lt")
// You should now get the values for the "lt" locale.
print(firstLinkedEntry.fields)
```

Let me know if that works.

**Comment by tadasz** [comment]
thank you sir it works, saved my day!

**Comment by loudmouth** [comment]
👏 woot. glad things are working for you now :-)

closing this for now
