### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by deepp** [contentful/contentful.swift#14]
Hi, I am working on tvOS app,earlier I used ContentfulDeliverAPI pod for iOS, Now I tried to use this repo for tvos but it throws error when I import it. Or should I be using this repo for tvos [https://github.com/contentful/tvful]. Please advice.

**Comment by loudmouth** [comment]
Hi @deepp, the ContentfulDeliverAPI is an Objective-C library. Did you give this one a try? It should work.

**Comment by loudmouth** [comment]
@deepp, this repo should indeed build for tvOS using Cocoapods. [`v0.3.1`](https://github.com/contentful/contentful.swift/releases/tag/0.3.1) just added support to install for tvOS via Carthage as well. 

Were you ever successful in installing for tvOS?
