### ISSUE TITLE
Disable code coverage in test scheme

### ISSUE THREAD

**Issue by shmigheghi** [contentful/contentful.swift#148]
> - contentful.swift version number: 0.8
> - Xcode version number: 9.0
> - Target operating system(s) and version number(s)
    - [ x ] iOS: 11.0

> - Package manager:
    - [ x ] Carthage

Please disable 'Gather coverage data' by default in the Test scheme - when using Carthage it can cause a submission error (`Invalid Bundle - Disallowed LLVM instrumentation`) when submitting a build with Xcode 9 that contains the contentful framework.

Technical details here: 
https://forums.developer.apple.com/thread/81893

**Comment by loudmouth** [comment]
Hey @shmigheghi I'm not familiar with this issue.

The "Gather coverage data" is turned on only for the main targets in project, not for the test targets. I'm a little unclear on if the issue you are describing is relevant to the main target or the test target. Can you confirm which one?

Also, does this issue persist in newer versions of the SDK? 1.0.0-beta1 was posted yesterday.

**Comment by shmigheghi** [comment]
Resolved: Updating Carthage to 0.26.0 or newer fixes this issue.
