### ISSUE TITLE
Swift 3.0 support in general

### ISSUE THREAD

**Issue by sigursalt** [contentful/contentful.swift#15]
Hi,

I see the Carthage and Cocoapods installation for Swift 3 is not yet supported for Contentful.

Is there another way to install this Swift 3 branch that is supported / working?

**Comment by mariobodemann** [comment]
Hey @sigursalt,

we are actively working on our Swift 3 support. Sadly I cannot disclose any time line as of yet. Please stay tuned....

Greetings,
Mario
