### ISSUE TITLE
Query result - fields that're arrays of Assets aren't mapped into objects

### ISSUE THREAD

**Issue by marcin-b-softnauts** [contentful/contentful.swift#153]
> - contentful.swift version number: 1.0.0-beta1
> - Xcode version number: 9.0.1 (9A1004)
> - Target operating system(s) and version number(s)
    - [ ] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [x] macOS: 10.12
> - Package manager:
    - [ ] Carthage
    - [x] Cocoapods

Hello,

It seems that if you have model that has a field which is an array of `Asset`s then those assets are not map into objects.

Please check the code below. I have entity `SomeModel` with `topImages` field which is always mapped to `nil`. The other field named `topVideo` which points to a single `Asset` is mapped correctly.

```
final class SomeModel: EntryDecodable, ResourceQueryable {
    static let contentTypeId: ContentTypeId = "pregnancyAndBaby"
    
    let sys: Sys

    var topVideo: Asset?
    var topImages: [Asset]?
    
    public required init(from decoder: Decoder) throws {
        sys = try decoder.sys()
        let fields = try decoder.contentfulFieldsContainer(keyedBy: SomeModel.Fields.self)

        try fields.resolveLink(forKey: .topVideo, decoder: decoder) { [weak self] topVideo in
            self?.topVideo = topVideo as? Asset // mapped correctly
        }
        try fields.resolveLinksArray(forKey: .topImages, decoder: decoder) { [weak self] topImages in
            self?.topImages = topImages as? [Asset] // not mapped at all, it's nil (!)
        }
    }
    
    enum Fields: String, CodingKey {
        case topImages, topVideo
    }
}
```

I fetch entities using the following code:

```
func fetchSomeEntries(completion: @escaping((Bool, [SomeModel]) -> ())) {
    let query = QueryOn<SomeModel>()
    client.fetchMappedEntries(matching: query) { (result: Result<MappedArrayResponse<SomeModel>>) in
        switch result {
        case .success(let itemsResonse):
            completion(true, itemsResonse.items)
        case .error(let error):
            print("Error fetching entries: \(error)")
            completion(false, [SomeModel]())
        }
    }
}
```

The problem is that `resolveLinksArray` callback returns `topImages` as `Any` and it fails:
`self?.topImages = topImages as? [Asset]`

What is more when I have a field which is an array of my custom entries (for instance `[SomeOtherEntries]`) it gets mapped correctly. So it seems that mapping does not work for `[Asset]`.

Is that a bug in SDK? Or maybe `topImages` should be resolved in a different way in `SomeModel` constructor?

**Comment by loudmouth** [comment]
Hi @marcin-b-softnauts , 

I've have had a very busy calendar the past few days so apologies for the delayed reply. Seems quite likely that you've identified a bug—I'll investigate get a fix out later in the week

Thanks the descriptive report :-)

**Comment by loudmouth** [comment]
Hi @marcin-b-softnauts, apologies for the delay. I have just investigated and I cannot confirm the issue in the SDK. A look at the code showed no indication that the issue you described with deserializing links of assets exists. While there was previously no test case for this scenario, I have just added one and indeed, a field linking to an array of assets properly resolves the link on the models in my test case.

I would recommend taking a look at what data you expect and if you have the correct field name for your `topImages` property. Perhaps it's something different in the Contentful web app?

If you can't resolve this issue yourself, I will likely need to know something about your content model and space. Don't hesitate to reach out to [Contentful support](https://support.contentful.com) where we can help further.

**Comment by marcin-b-softnauts** [comment]
Hello @loudmouth,

Thanks for the replies.

I've checked the issue. When I was creating an iOS app or macOS it worked - assets are mapped. But when I created Command Line Tool (it was my case) - assets are not mapped. 

Probably the problem was that I embeded [contentful.swift](https://github.com/contentful/contentful.swift) using Cocoapods that has poor support for command line tools [https://github.com/CocoaPods/CocoaPods/issues/3707](https://github.com/CocoaPods/CocoaPods/issues/3707).

When I embeded [contentful.swift](https://github.com/contentful/contentful.swift) using Swift Package Manager the issue didn't exist. So I'm closing the issue.

**Comment by loudmouth** [comment]
Interesting. I have also found that SPM is better suited for developing Command Line Tools with Swift. It's good to be aware of possible issues with Cocoapods.

Thanks @marcin-b-softnauts !
