### ISSUE TITLE
Use of undeclared type 'ResourceQueryable'

### ISSUE THREAD

**Issue by eytanschulman** [contentful/contentful.swift#156]
> - contentful.swift version number: 0.11.0
> - Xcode version number: 9.2
> - Target operating system(s) and version number(s)
   - [x]  iOS: 11.2
> - Package manager:
   - [x]  Cocoapods: 1.3.1

When attempting the example written in the READMe file on this repository, I get this error: Use of undeclared type 'ResourceQueryable'.

I did some quick digging to see that the ResourceQueryable protocol is implemented in a Swift file called [TypedQuery.swift](https://github.com/contentful/contentful.swift/blob/master/Sources/Contentful/TypedQuery.swift). When looking at my Contentful installation in my Xcode project, I do not see this file, and therefore Xcode does not see this protocol implementation.

I tried removing Contentful as a pod and readding, but to no avail the problem persists. 

How can I get the TypedQuery.swift file into my project via Cocoapods?

**Comment by loudmouth** [comment]
Hi @eytanschulman 

Upgrade to the [1.0.0-beta3](https://github.com/contentful/contentful.swift/releases/tag/1.0.0-beta3), the latest release version of the SDK, to use the code described in the README:

In your Cartfile you can use the following line:

```
github "contentful/contentful.swift" "1.0.0-beta3"
```

**Comment by eytanschulman** [comment]
Thank you!

I messed up in my original post and left the Carthage mention there.. I’m using Cocoapods. How would I install the beta through cocoapods?

**Comment by loudmouth** [comment]
Ahh ok no problem:

```ruby
pod 'Contentful', ~> '1.0.0-beta3'
```

Sorry for the delayed response btw. Let me know how that works out.

**Comment by loudmouth** [comment]
Everything work out @eytanschulman ?

**Comment by eytanschulman** [comment]
Sorry about that, just got a chance to try it out. Thanks @loudmouth !
