### ISSUE TITLE
Cannot mapping entries

### ISSUE THREAD

**Issue by gauuni** [contentful/contentful.swift#160]
Hi team, 

Do you still support this lib?

I'm using your project but it's crashed here:

let contentTypes = decoder.userInfo[DecoderContext.contentTypesContextKey] as! [ContentTypeId: EntryDecodable.Type]

in ArrayResponse.swift

Beside you Readme is outdated. Please support
Thanks

**Comment by loudmouth** [comment]
Hey @gauuni 

This repo is indeed maintained. Given the crash you're experiencing, I would imagine that you're trying to use the methods that return entries mapped to your own types.

The crash suggests that you have not passed in any types that conform to `EntryDecodable` to your instance of `Contentful.Client`: makes sure to pass your class into the initializer like so:

```swift
// Pass in your declared classes here.
let contentTypeClasses: [EntryDecodable.Type] = [Post.self, Author.self]
let client = Client(spaceId: "<your_space_id>",
                    accessToken: "<your_access_token>",
                    contentTypeClasses: contentTypeClasses)
```

You can see some examples in the tests [here](https://github.com/contentful/contentful.swift/blob/master/Tests/ContentfulTests/QueryTests.swift#L96)

**Comment by gauuni** [comment]
Thanks a lot for your helping. You saved my day.
