### ISSUE TITLE
Instructions on spaceId & API access token configuration...

### ISSUE THREAD

**Issue by zenevate** [contentful/contentful.swift#163]
Fill in the following details, then delete this line before submitting. (To mark a checkbox change `- [ ]` to `- [x]`).
> - contentful.swift version number: 
> - Xcode version number:
> - Target operating system(s) and version number(s)
    - [ ] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [ ] Carthage
    - [ ] Cocoapods

 Just spent 15 minutes digging around on how to set these up with the cocoapod. I'm sure I could figure it out eventually.. but could you guys just add this to the README? Thanks!

**Comment by loudmouth** [comment]
Hey @zenevate thanks for bringing this up. I think you're totally correct and I've just added instructions in #165 

Sorry for the trouble.
