### ISSUE TITLE
Unable to integrate Contentful Cocoapod into project.

### ISSUE THREAD

**Issue by jyaunches** [contentful/contentful.swift#164]
Ok, so.. I totally love the idea of this tool! I can't get it working. There's also disparate documentation between your website & github.

Alright.. 

## First attempt.

Step 1 -> Add Podfile entry

pod 'Contentful'. (FYI, this got me version 0.11.0)

Step 2 -> Reference this documentation: https://www.contentful.com/developers/docs/ios/tutorials/using-delivery-api-with-swift/

Step 3 -> Observe error using code from example ['type Cat does not conform to protocol Resource']

![screen shot 2018-01-17 at 9 48 19 am](https://user-images.githubusercontent.com/372490/35050605-36cf2ca4-fb71-11e7-8e25-22da4ac39586.png)

I dug in and tried adding the 'sys' variable.. because that seemed like it could be the missing expectation from the protocol.. but that didn't work.

## Next attempt.

Reviewed the README on the github page. Noticed there it says to use 'EntryDecodable, ResourceQueryable' as protocols on your models. So, I did that!

Still on pod version 0.11.0. But updated to use these.

Getting an error 'undeclared resource 'ResourceQueryable'.

Searching through the Pod headers... there is indeed no reference to this protocol.

## Next attempt.

Ok, so I noticed in your example project that your pointing to master.. this obviously makes me extremely nervous, but I decided to try it out. Wa-la! Now ResourceQueryable is indeed included in the pod headers.

However.. now I get an exception on a forced unwrapping.

![screen shot 2018-01-17 at 10 20 46 am](https://user-images.githubusercontent.com/372490/35051174-9a6718a2-fb72-11e7-9c15-3d58d692be6b.png)

## So Question

Is this cocoapod in a usable state at it's current head? If so, can you point me to the accurate documentation for using it?

I noticed master is implying a version of 1.0. Indicating that you're thinking you'll reach 1.0 in your next release. Is it in my best interest to just wait for that?

**Comment by loudmouth** [comment]
Hey @jyaunches !

I'm excited that you're trying out the SDK! Currently the latest version of the Contentful Cocopod is actually `1.0.0-beta5` and it is stable! (`1.0.0` is likely to be released next week).

It's recommended to use the example Podfile line that [can be found in the README in the 'Cocoapods installation' section:

```
pod 'Contentful', '~> 1.0.0-beta5' 
```

For some reason pointing to the newest pod doesn't give versions that have status-modifiers like `-beta1` but publishing still workds.

Use the newest version :-)

You'll want your entry model classes to conform to two protocols to use queries and to have them mapped properly: `ResourceQueryable & EntryDecodable`

Let me know how everything works out!

**Comment by loudmouth** [comment]
Hey @jyaunches !

I'm excited that you're trying out the SDK! Currently the latest version of the Contentful Cocopod is actually `1.0.0-beta5` and it is stable! (`1.0.0` is likely to be released next week).

It's recommended to use the example Podfile line that [can be found in the README in the 'Cocoapods installation' section:

```
pod 'Contentful', '~> 1.0.0-beta5' 
```

For some reason pointing to the newest pod doesn't give versions that have status-modifiers like `-beta1` but publishing still workds.

Use the newest version :-)

You'll want your entry model classes to conform to two protocols to use queries and to have them mapped properly: `ResourceQueryable & EntryDecodable`

Let me know how everything works out!

**Comment by jyaunches** [comment]
Hi there! Apologies for the delay in response.. Wasn't able to attempt to
move to the branch you mentioned until this morning..

So, just a heads up.. the following will be descriptions of what going on
when I'm trying to use two versions of your SDK.

My root problem is that in neither case do I have success in either basic
querying or querying with filters.. which I need to be able to do!

Case 1 -

pod 'Contentful', '~> 1.0.0-beta5'

On setting up my query to follow the example on your github README, I'm
getting a non-descript error that the JSON is not parseable. However, I've
kept my model super simple.. just trying to deserialize 3 string fields
right off the bat.

[image: Inline image 1]


Case 2 -

pod 'Contentful'

I've been integrating for now using this version. I do have it working...
until I add a filter. (i.e. additional query parameters)

In this implementation.. I just grab the first instance of the model that's
returned and deserialize it myself.

[image: Inline image 5]

I'm happy to do the deserialization... What I really need is the
flexibility to specify things in the query.. Like fetch this model where
emailAddress == 'blah@gmail.com'.

In this version.. the when I try to add a filter.. I get the following
error saying it's an invalid query.

[image: Inline image 6]

When the model defined in the Contentful web interface clearly does match
the query.

[image: Inline image 4]

--------------------------------------------------------

Again, I'm happy to do my own deserialization.. I just need to be able to
add filters to queries and I'm not able to do that with either version of
the SDK! Please inform me on what needs to happen!

**Comment by loudmouth** [comment]
Hey @jyaunches, I've encountered those errors before: unfortunately, those errors are actually returned by `Swift.Foundation` and I agree that they're difficult to read. I think in the future I'll try to intercept errors from `Swift.Decodable` and manipulate them to be more readable. In the meantime...

you're images aren't being rendered by Github—probably because it looks like you replied via email and the images weren't uploaded...can you edit your response above so I can get a better idea of what's going one?

**Comment by jyaunches** [comment]
Hi there! Apologies for the delay in response.. Wasn't able to attempt to
move to the branch you mentioned until this morning..

So, just a heads up.. the following will be descriptions of what going on
when I'm trying to use two versions of your SDK.

My root problem is that in neither case do I have success in either basic
querying or querying with filters.. which I need to be able to do!

Case 1 -

pod 'Contentful', '~> 1.0.0-beta5'

On setting up my query to follow the example on your github README, I'm
getting a non-descript error that the JSON is not parseable. However, I've
kept my model super simple.. just trying to deserialize 3 string fields
right off the bat.

![screen shot 2018-01-30 at 12 29 43 pm](https://user-images.githubusercontent.com/372490/35647109-81f3f596-069f-11e8-8a4d-ed70d9e19f10.png)

Case 2 -

pod 'Contentful'

I've been integrating for now using this version. I do have it working...
until I add a filter. (i.e. additional query parameters)

In this implementation.. I just grab the first instance of the model that's
returned and deserialize it myself.

![image](https://user-images.githubusercontent.com/372490/35647140-a0bbf0a0-069f-11e8-967c-f15acdce8467.png)

I'm happy to do the deserialization... What I really need is the
flexibility to specify things in the query.. Like fetch this model where
emailAddress == 'blah@gmail.com'.

In this version.. the when I try to add a filter.. I get the following
error saying it's an invalid query.

![screen shot 2018-01-30 at 12 46 42 pm](https://user-images.githubusercontent.com/372490/35647169-ad61d70c-069f-11e8-8daf-694f6de14a28.png)

When the model defined in the Contentful web interface clearly does match
the query.

![screen shot 2018-01-30 at 12 43 04 pm](https://user-images.githubusercontent.com/372490/35647194-bbf92a2c-069f-11e8-8c85-f4232e7dc171.png)

**Comment by jyaunches** [comment]
That looks like it got the images in! Let me know if that's clear. Thanks a lot for the prompt support!

**Comment by loudmouth** [comment]
Hi @jyaunches 

So, firstly i thought i'd let you know that `1.0.0` of the SDK was released last week. In fact i published [`1.0.1`](https://github.com/contentful/contentful.swift/releases/tag/1.0.1) yesterday. I recommend using that version ;-) 

Secondly, you can edit your query to look like the following with the newest SDK:

```swift
let query = QueryOn<Practitioner>.where(field: .emailAddress, .equals("blah@gmail.com"))
query.include(4)
```

Now, onto the problems: I'm going to skip the cases you layed out for now because I think the main issue is that your content type id is incorrect. Since your space id and access token is public in the image, I went ahead and introspected your content type and indeed the id for your `Practitioner` type starts with a lower case "p" (P.S. I recommend revoking that Delivery Token and creating a new one since the entire world can see it on Github now; even though it's a read-only token).

```swift
static let contentTypeId = "practitioner"
```

I'm quite sure that should fix it, but the strange thing is that you didn't get the error back from the API in the first place. I think there is some weirdness happening with the interaction between your dependency on RxSwift and Contentful. For instance, the pattern for the result that Contentful gives back is to `switch` on the result. I'm not sure what the `.get()` method is doing, but it seems as if it's trying to deserialize again after the SDK has already (probably) deserialized an `APIError` type. When it attempts to deserialize a `MappedArrayResponse` it correctly cannot find the `"skip"` parameter in the payload because it is actually an APIError.

If you _do_ want to try to avoid using `EntryDecodable` your query would like like follows with version >= `1.0.0` of the SDK. Note that "fields." is prepended to the actual field:

```
let query = Query.where(contentTypeId: "practitioner)
query.where(valueAtKeyPath: "fields.emailAddress", .equals("blah@gmail.com"))
query.include(4)
```

**Comment by loudmouth** [comment]
Hey @jyaunches 

Did you get this sorted out?

**Comment by jyaunches** [comment]
Ok, so I updated to the latest cocoapod and was able to retrieve records. YES!

I'm now beginning to work on persisting new records. Is this possible with the cocoapod? Would I use: persistenceIntegration?

**Comment by jyaunches** [comment]
I have deduced from various documentation that entry creation will have to be done via the content management api. Which I'm happy to do from the app via standard networking calls! Thanks a lot for the support here! It's very appreciated.

**Comment by loudmouth** [comment]
Hey @jyaunches, if you need to persist your data, check out [contentful-persistence.swift](https://github.com/contentful/contentful-persistence.swift). It is an implementation of `PersistenceIntegration` and currently only supports using the [`/sync` endpoint](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/synchronization) of the Content Delivery and Content Preview APIs.

You will need to setup your own Xcode data model and write your own `NSManagedObject` subclasses for your models. Also, a solid understand of CoreData will greatly facilitate development.

Good luck!

**Comment by jyaunches** [comment]
Yes, I am interested in persisting to the Contentful end only. I do not want to introduce CoreData into that app at the moment.

**Comment by loudmouth** [comment]
Ah, so by 'persisting' you meant PUT/POST to the Contentful Management API. Understood! 👍 

Good luck and don't hesitate to reach out to https://support.contentful.com if you need help!
