### ISSUE TITLE
Retrieving a random entry

### ISSUE THREAD

**Issue by Wouter125** [contentful/contentful.swift#190]
> - contentful.swift version number: 
> - Xcode version number:
> - Target operating system(s) and version number(s)
    - [ ] iOS: 
    - [x] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [ ] Carthage
    - [x] Cocoapods

This might be more of a feature request than an issue, but I would like to leave it here for now. I'm having a growing database of let's say 1200 entries within a content type. This might even grow to 10k or more in the next couple of months. The thing is, I would like to fetch a couple of random entries, e.g. 1-5 or so from these 1200 entries.

To do so I'm required to retrieve all 1200 entries and manipulate all data on the client side right now. As the entries will be growing this will cause delays and require a lot of data from the users device. 

To solve this I came up with something like this but not all of it is possible with the current API;

1. Getting the total of entries in a content type with one call (without all entries).
2. Generate a couple of random numbers on the clientside that lay within the number of entries.
3. Use these random numbers in the skip parameter (as array so I only need one call) and set the limit of entries that I would like to retrieve to the number of my array length.

So would it be possible to retrieve a single / multiple random entry without having to retrieve the full list of entries?

Thanks in advance.

**Comment by loudmouth** [comment]
Hi @Wouter125 

I think this qualifies more as a feature request for our API team: fetching a random entry. I can try to pass it along, but i'm not sure it warrants an ever-open Github issue...

Actually, in discussing with some of the other members of the SDK team, your solution is totally feasible and should result in just 2 API requests for each random entry you want.

1. Getting the total of entries in a content type with one call, but don't fetch the entries themselves.

```swift
fetchMappedEntries(matching: QueryOn<Cat>.limit(to: 0)) { result in
    // because you limited to 0, you will have 0 items in the `ArrayResponse`
    let totalNumberOfCats = result.value?.total
}
```

i.e. the response looks something like this;

```json
{
    "sys": {
        "type": "Array"
    },
    "total": 5493,
    "skip": 0,
    "limit": 0,
    "items": [ ]
}
```

2. Generate a couple random numbers...
I think you have this part ;-)

3. Use these random numbers in the skip parameter and set your limit to match your 

```swift
fetchMappedEntries(matching: QueryOn<Cat>.skip(theFirst: yourRandomNumber)) { result in
    switch result {
        case .success(let arrayResponse):
             let randomCat = arrayResponse.items.first!
        case .error(let error):
            print(error)
    }
    let totalNumberOfCats = result.value?.total
}
```

**Comment by Wouter125** [comment]
You are right! It should have been asked on the API part of contentful. Sorry about that. But the solution you proposed here works perfectly. I just didn't know you were able to fetch 0 items in the array response. Thanks. I think we can close this one as well!
