### ISSUE TITLE
Asset.swift only supports images

### ISSUE THREAD

**Issue by rdas-deloitte** [contentful/contentful.swift#192]
Ever since 0.93 there was a change to how Assets are deserialised that results in only image assets being supported.

In Asset.swift: 66 - file is found to be nil, since the dictionary does not successfully map to type FileMetadata.

**Comment by loudmouth** [comment]
The fix is also tested btw—let me know after you have the time to upgrade to 2.0.0 and if all is good, we can close this issue.

**Comment by rdas-deloitte** [comment]
I'll give it a whirl. I love you, but you guys so badly need to update your docs 🤦‍♂️

**Comment by loudmouth** [comment]
Hey @rdas-deloitte ,

Can you be more specific on what's lacking with our documentaiton? The SDK has 100% documentation coverage of all public properties, methods (you can browse it with Xcode or [here](https://contentful.github.io/contentful.swift/docs/index.html): i need to add a link to this doc to the readme: see #178 ). With the exception of a few outdated example apps being available at https://www.contentful.com/developers/docs/ios/ everything there is up-to-date.

The API reference documentation for our 4 API offerings is also up-to-date. Anyway, without specific feedback, there is not much change I can help you effect.

**Comment by loudmouth** [comment]
(And PR or our documentation which updates the swift tutorial for the 2.0.0 release will be merged today: only a few hours after it was published)

**Comment by rdas-deloitte** [comment]
Thanks JP just trying to keep up with the changes! 😄 Is there a 1.0 to 2.0 migration guide?

**Comment by loudmouth** [comment]
Now that sounds like something that could be useful. I can try to add a migration guide this week :-) Just added #193 to keep track of things.

In the meantime, the breaking changes are listed in the [changelog](https://github.com/contentful/contentful.swift/blob/master/CHANGELOG.md#200) 

I have a guess that the only two that may have affected your code are those pasted below, but better to check the full list in the changelog to be sure. 

- **BREAKING:** The interface for synchronization has been simplified. `initialSync` and `nextSync` have been replaced with `sync` with a default argument of an empty sync space to start an initial sync operation.
- **BREAKING:** `ResourceQueryable` has been renamed `EntryQueryable` for correctness and consistency.

I'll close this issue for now, and tag you when i get a migration guide up
