### ISSUE TITLE
Fetch mapped entry by id

### ISSUE THREAD

**Issue by gmarm** [contentful/contentful.swift#194]
> - contentful.swift version number:  2.0.0
> - Xcode version number: 9.3 (9E145)
> - Target operating system(s) and version number(s)
    - [x] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [ ] Carthage
    - [x] Cocoapods

I have a question regarding the SDK's public API.

I'm in the process of moving away from fetching `Entry` types to actual mapped entries. Basically the part "A more refined approach" in your [Swift tutorial page](https://www.contentful.com/developers/docs/ios/tutorials/using-delivery-api-with-swift/).

I was a bit puzzled to see that there are a few `fetchMappedEntries()` methods, but no `fetchMappedEntry(id: String)` method. 

Is there a way I can get a mapped entry by id somehow?

**Comment by loudmouth** [comment]
Hi @gmarm 

You're totally correct! Luckily this should be quite easy to achieve with the following `QueryOn`

```swift
let query = QueryOn<MyType>.where(sys: .id, .equals("<entry_id>"))
fetchMappedEntries(matching: query) { ...
```

This resolves to a query that looks like this: 

```
https://cdn.contentful.com/spaces/<space_id>/environments/master/entries?sys.id=<entry_id>
```
the benefit of using the `sys.id=<entry_id>` as opposed to `/entries/<entry_id>` is that you actually get one level of [includes](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links/retrieval-of-linked-items) so the first level of related entries & assets is automatically included in the response and resolved for you.

**Comment by gmarm** [comment]
Sounds good! 

Thanks for the quick reply, closing this!
