### ISSUE TITLE
Timezone issue using default date decoding strategy

### ISSUE THREAD

**Issue by kedio** [contentful/contentful.swift#196]
> - contentful.swift version number: 2.1.0
> - Xcode version number: 9.3
> - Target operating system(s) and version number(s)
    - [x] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [x] Carthage
    - [ ] Cocoapods

Example of string returned by contentful API: "2018-06-06"
Output of `print(date)` (Where "date" is the Date object created by the default decoder strategy): "Optional(2018-06-06 00:00:00 +0000)"

Output of `print(date)` (Where 'date' is the Date object created by my custom decoder strategy): "Optional(2018-06-06 03:00:00 +0000)"

The user timezone does not seem to be accounted for in the default decoder.

Here is my current decoder strategy:
```
    private let supportedDateFormat = [
        "yyyy-MM-dd'T'HH:mm:ss.SSSXXXXX",
        "yyyy-MM-dd",
        "yyyy-MM-dd'T'HH:mm",
        "yyyy-MM-dd'T'HH:mmZ"
    ]

    private let dateFormatter = DateFormatter()

    private init() {
        var configuration = ClientConfiguration()
        configuration.dateDecodingStrategy = .custom { decoder in
            let container = try decoder.singleValueContainer()
            let dateString = try container.decode(String.self)

            for format in self.supportedDateFormat {
                self.dateFormatter.dateFormat = format
                guard let date = self.dateFormatter.date(from: dateString) else { continue }
                return date
            }
            throw Date.Error.unsupportedDateFormat
        }
        
        client = Client(spaceId: ContentfulService.spaceId,
                        accessToken: ContentfulService.accessToken,
                        clientConfiguration: configuration,
                        contentTypeClasses: ContentfulService.contentTypeClasses)
    }
```

**Comment by loudmouth** [comment]
Hey @kedio, thanks for opening a new issue 🙂 

To confirm a few things, by "default decoder strategy" do you mean the one that is configured by default on new `Contentful.Client` instances?

Secondly, I'm a little confused in terms of your expectations. `2018-06-06 00:00:00 +0000` seems like an exact representation (albeit with more information: hrs, mins, sec) of  `"2018-06-06"` that is being returned by the API. Why is the `2018-06-06 03:00:00 +0000` 3 hour difference important to you here?

**Comment by kedio** [comment]
Hey @loudmouth, thanks for the quick reply!

Yes by default strategy I mean using the client without custom configuration.

I'm pretty sure the inconsistency I experience is due to this [line](https://github.com/contentful/contentful.swift/blob/bcf2808cf2a51543fc3a755663b47d67c3a1b42e/Sources/Contentful/Date.swift#L40). 
Instead of using the user timezone the default strategy uses a timezone of 0.

It may be a case by case issue and I don't know what the expected behavior should be. But in my current use case after parsing a date using the default strategy, when I format the date using the user timezone afterward I get unexpected results.

**Comment by loudmouth** [comment]
I'm sorry @kedio but I'm still a little confused by what exactly you're expecting and why. Please bear with me :-)

As I understand ISO: the `+0000` is the representation of the timezone offset, with `+0000` representing UTC time. When implementing this in the SDK, it was my opinion that a date without hours, minutes, seconds or timezone offset should be normalized to UTC time. With this reasoning,
`"2018-06-06"` should resolve do a date `2018-06-06 00:00:00 +0000`.

Reading your responses, it seems to me like you believe the correct date should be 3AM or `03:00:00` rather than a date that empty information for hours:minutes:seconds. Would you be able to elaborate on why having a 3 hour offset (not represented in the timezone, but actually a 3 hour offset) is a better representation of a date without hours:minutes:seconds such as `"2018-06-06"`?

**Comment by kedio** [comment]
The "Optional(2018-06-06 00:00:00 +0000)" and "Optional(2018-06-06 03:00:00 +0000)" was just me trying to explain that the swift Date object created by the default strategy and my custom strategy is different. Date object is just a number of seconds, but that number changes depending on how the date formatter is configured either to parse a string to a Date or format a Date to a string. The problem here is not using the same formatter to parse (when getting data from Contenful) and to format (when displaying a date to the user). 

So I don't know what should be the expected behavior. Usually, I always use the user timezone to format my dates but it may be different for others.

**Comment by loudmouth** [comment]
Ok. Now things are more clear. Maybe the best way forward is to simply use one shared instance of the `DateFormatter` and expose it (as opposed to generating a new one for each date decoding call) within the `variableISO8601Strategy` so that the SDK consumer can configure the TimeZone on their own but still take advantage of the implementation of the strategy. This would also probably improve performance a little bit.

Do you think this would solve your problem?

**Comment by kedio** [comment]
Yes, this would solve my problem! It may also improve performance like you said. Maybe there is some thought to but put into what should be the default dateFormatter. It can create subtle bugs like in my case displaying an event date a day early! So the default dateFormatter should be the most expected one, my personal opinion is that it should be the user time zone and the user locale. But, it may be a big change and break current implementations that expect the default timezone to be 0.

Let me know what you think.

**Comment by loudmouth** [comment]
You're definitely right that this requires some thought. I will make sure to post a proposal with reasoning before going through with implementation.

Thanks for all the feedback so far @kedio

**Comment by loudmouth** [comment]
Hey @kedio 

I just discussed with my colleagues about how to handle this. The beauty of using TimeZone offset of 0 is that the exact representation of the date returned by the API is forwarded to the application. What you get in, is what you get out.

However, we fully recognize that this does not fit all use cases. So, the solution we'll move forward with is enabling a `TimeZone` configuration on the Client. You'll be able to basically tell the SDK to use `TimeZone.current` (the system timezone) as opposed to the SDK default, which will remain 0 sec offset from GMT.

Stay tuned for a PR.

**Comment by kedio** [comment]
Hi @loudmouth 

It is starting to make sense to me why it is a good practice to use TimeZone offset of 0 until we want to display a date to the user (given we actually want the date to be displayed in the user TimeZone). So all this started because I needed to use a custom date decoding strategy which should have used the same timezone as the rest of the SDK. 

We actually don't want to take the timezone into account for our use case. We want the date we put in contentful to be the date displayed in the application regardless of the timezone. So I'm now realizing that using the default dateFormater (defaulting to the user timeZone) should not have been my go-to formatter. 

I think that using offset 0 throughout the SDK is the best approach and now I'm wondering if adding the possibility of changing the TimeZone globally would just add more confusion as to how the SDK should be used.

Maybe instead the way to go is to make sure the timezone cannot be changed like I did by customizing the dateFormatter so everything is always consistent with the rest of the SDK. (I don't know if that is possible)

Sorry for the back and forth I'm also learning as we go!

**Comment by loudmouth** [comment]
> Maybe instead the way to go is to make sure the timezone cannot be changed like I did by customizing the dateFormatter so everything is always consistent with the rest of the SDK. (I don't know if that is possible)

Hmm, I'm not sure if it's possible to enforce both enabling a custom `DateFormatter` or `DateDecodingStrategy` (which I do think is valuable for certain scenarios) while simultaneously enforcing a 0 offset `TimeZone` is used.

That being said, in discussion on our end, we think it is valuable to enable injecting a custom `TimeZone` as long as it has a 'sane' default—the sane default of choice is of course 0 seconds offset from GMT. This configuration option is added in #207

**Comment by kedio** [comment]
Yep, I think that makes sense! 
Thank you for the ongoing support!

**Comment by loudmouth** [comment]
[`2.2.0`](https://github.com/contentful/contentful.swift/releases/2.2.0) is now available on Cocoapods and precompiled binaries are available through Carthage! 🎉
