### ISSUE TITLE
Synchronization not completed

### ISSUE THREAD

**Issue by marcin-bo** [contentful/contentful.swift#203]
Hi,

We have a lot of data to synchronize it seems that sometimtes synchronization ends too early, before downloading all data (completion handler is called by sync function). Only after re-running the synchronization process it downloads the rest of data. For instance:

1. When I run app for the first time it calls `sync(for syncSpace:syncableTypes:then:)` function three times. Then it calls completion handler. So it seems that sync is done. But some data is missing.

2. After restarting the app and running synchronization process it calls `sync(for syncSpace:syncableTypes:then:)` function ten times, then itcalls completion handler, and we see that all data is downloaded.

Is that a normal behaviour or a bug in the library?

We use contentful.swift (2.0.0) as a dependency of ContentfulPersistance library.

> - contentful.swift version number: 2.0.0
> - Xcode version number:
> - Target operating system(s) and version number(s)
    - [x] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [ ] Carthage
    - [x] Cocoapods

**Comment by loudmouth** [comment]
Hey @marcin-bo ,

The `sync(for:syncabaleTyes:then)` method is recursive: it will make a call for each page that is returned until all pages of a sync operation have been returned. So, it is normal behavior that the method should be called so many times. 

The SDK "knows" there is another page available if there is a `nextPageUrl` returned in the payload and if the `nextSyncUrl` is absent from the payload. The completion handler will only be called in the opposite situation: when a `nextSyncUrl` _is_ present and `nextPageUrl` is absent. It shouldn't be possible for the completion handler to be called without this condition being true. So, before we can decidedly say there is a bug, can you confirm that there are more pages (i.e. `nextSyncUrl == nil` and `nextPageUrl != nil` right before your unexpected completion handler is called?

**Comment by loudmouth** [comment]
@marcin-bo 

I wanted to check in on this and see if you were able to confirm whether or not there is a bug, i.e. that there are more pages, `nextSyncUrl == nil` and `nextPageUrl != nil` right before your unexpected completion handler is called?

**Comment by marcin-bo** [comment]
It's hard to recreate this issue. Maybe this is an issue with API, not sure. I'll observe how synchronization behaves in incoming days and I'll let you know.

**Comment by marcin-bo** [comment]
I think I mixed spaces and that was the reason of the issue (we use two spaces: one for development and one for production). So I will close the issue.

**Comment by 1abhisheksingh** [comment]
Hey Marcin, What do you mean by "mixed spaces" ? I am also having issue of synchrnization not completed. I am to implement two spaces to sync the data. I am using offline persistent + coredata.
PLease let me know,  how you resolved it.

**Comment by marcin-bo** [comment]
Hi, I was connecting to the wrong space - I expected to get data from the production space but I was syncing with development space.
