### ISSUE TITLE
Resolving a Link with references, many

### ISSUE THREAD

**Issue by Wouter125** [contentful/contentful.swift#204]
Fill in the following details, then delete this line before submitting. (To mark a checkbox change `- [ ]` to `- [x]`).
> - contentful.swift version number: 
> - Xcode version number:
> - Target operating system(s) and version number(s)
    - [ ] iOS: 
    - [x ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [ ] Carthage
    - [x ] Cocoapods

I think this is a short question, but I can't seem to figure this out. I'm having 2 content models Song and Artist. When I'm fetching Song, Artist is linked and I can easily resolve it's contents like this;

```
try fields.resolveLink(forKey: .artist, decoder: decoder) { [weak self] linkedArtist in
   self?.artist = linkedArtist as? ArtistModel
}
```

But within Song I'm also having a Featured Artists linked (References, many) which is basically an array of artists conforming to the ArtistModel. I tried resolving it like this but I can't seem to get it to work;

```
try fields.resolveLink(forKey: .featuredArtist, decoder: decoder) { [weak self] linkedFeaturedArtist in
    self?.featuredArtist = linkedFeaturedArtist as? [FRArtistModel]
}
```

It results in the following error which probably makes sense;
`Expected to decode Dictionary<String, Any> but found an array instead.`

What am I doing wrong here? It's picking my brain for way too long now.

**Comment by loudmouth** [comment]
Hey @wouter I’m traveling today so excuse the small response as I’m on my mobile.The method you need is `resolveLinksArray`

You can see some example usage in this file:

https://github.com/contentful/contentful.swift/blob/master/Tests/ContentfulTests/EntryDecodableLinkResolutionTests.swift
