### ISSUE TITLE
Date as QueryableRange default time zone

### ISSUE THREAD

**Issue by kedio** [contentful/contentful.swift#205]
> - contentful.swift version number: 2.1.0
> - Xcode version number: 9.4
> - Target operating system(s) and version number(s)
    - [x] iOS: 11
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [x] Carthage
    - [ ] Cocoapods

We got another timezone related issue this weekend. 

The problem:
Stopped receiving a tournament a day early when creating a query with a date as the operation's QueryableRange. Here is an example of the query:
```
        let upNextQuery = QueryOn<ContentfulTournament>
            .where(field: .showInUpNext, .equals("true"))
            .where(field: .endDate, .isAfter(baseDate))
            .include(10)
        if let ordering = try? Ordered<ContentfulTournament>(field: .startDate) {
            upNextQuery.order(by: ordering)
        }

        client?.fetchMappedEntries(matching: query) { result in
            // use results
        }
```

Guess on the cause of the problem:
The stringValue of a date used as a QueryableRange is defined by iso8601String which use `TimeZone(secondsFromGMT: 0)` by default. In our current application, we use a different time zone by default.

**Comment by loudmouth** [comment]
Hey @kedio 

I realize i have left the timezone issue hanging for a few weeks now. I'll make sure to attend to it this week.

Cheers

**Comment by loudmouth** [comment]
Hey @kedio I'm going to close this issue and continue the discussion on #196
