### ISSUE TITLE
Contentful fails to build when being checked out via Carthage with Xcode 10

### ISSUE THREAD

**Issue by CharlesVu** [contentful/contentful.swift#231]
- contentful.swift version number: 3.1.2
- Xcode version number: 10.0
- Target operating system(s) and version number(s)
  - [X] iOS: 10.0
- Package manager:
  - [X] Carthage

`carthage update --cache-builds --platform iOS --use-ssh` fails with 

`
/usr/bin/xcrun xcodebuild -workspace <path>/Carthage/Checkouts/contentful.swift/Contentful.xcworkspace -scheme Contentful_iOS -configuration Release -derivedDataPath /Users/server/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/contentful.swift/3.1.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/m_/8swmb9_55c7d68ygn7t728p00000gn/T/contentful.swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in <path>/Carthage/Checkouts/contentful.swift)
`

The underlayed error is : 
`
<path>/Carthage/Checkouts/contentful.swift/Sources/Contentful/Client+Modellable.swift:10:8: error: module file's minimum deployment target is ios8.3 v8.3: /Users/server/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/contentful.swift/3.1.2/Build/Intermediates.noindex/ArchiveIntermediates/Contentful_iOS/BuildProductsPath/Release-iphoneos/Interstellar.framework/Modules/Interstellar.swiftmodule/arm64.swiftmodule
import Interstellar`

**Comment by loudmouth** [comment]
Hi @CharlesVu apologies for the delayed response; I had been on vacation.

I've yet to release a version of Contentful that is compatible with Xcode 19, but I will try to do so ASAP.

Hang tight.

**Comment by loudmouth** [comment]
[Version 4.0.0](https://github.com/contentful/contentful.swift/releases/tag/4.0.0) has just been published to Cocoapods; and binaries are available for carthage as well.
