### ISSUE TITLE
"Result of call to 'fetchEntries(matching:completion:)' is unused" warning

### ISSUE THREAD

**Issue by 6franek** [contentful/contentful.swift#24]
It would be nice if you add `@discardableResult` to the declaration of `fetch` functions, so that Swift 3 compiler doesn't complain about not using their results.

**Comment by loudmouth** [comment]
@6franek thanks for bringing this to my attention. Will patch this up right away.

**Comment by loudmouth** [comment]
@6franek, patch has been merged into `master` and should therefore be available for use.

I will be pushing out a dot release sometime in the next two weeks as well.
