### ISSUE TITLE
~> 4.0.0 autoupdate to 4.1.1 Deployment Target raised to 9.3

### ISSUE THREAD

**Issue by EternalBlack** [contentful/contentful.swift#241]
- contentful.swift version number: 4.1.1
- Xcode version number: 10.1 (19B61)
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [x] Carthage
  - [ ] Cocoapods

Just updated Contentful through carthage with `github "contentful/contentful.swift" ~> 4.0.0` inside the cartfile. I didn't really expect to have kind of a "breaking change" i.e. a raise in the `Deployment Target` to `9.3`. My project for a big client unfortunately depends on `9.0`. Are there any plans to keep support for 9.0 or is this final?

**Comment by loudmouth** [comment]
@EternalBlack it looks like at 4.0.0, and even 3.1.2, he deployment target for tvOS was 10.1. Are you sure you didn't have this issue on tvOS with 4.0.0?

**Comment by EternalBlack** [comment]
@loudmouth I'm sorry, didn't actually check for tvOS but for iOS it definitely currently is 9.3 instead of 9.0.

**Comment by loudmouth** [comment]
Is the current tvOS deployment target OK for you? The box is check in your original issue description.

**Comment by EternalBlack** [comment]
Yeah, sorry for the confusion. tvOS is fine for me as I'm using 12.0 currently anyway.

**Comment by loudmouth** [comment]
@EternalBlack [`4.1.2`](https://github.com/contentful/contentful.swift/releases/4.1.2) was just released 🎉
