### ISSUE TITLE
Crash when initializing Client

### ISSUE THREAD

**Issue by ericDMH** [contentful/contentful.swift#247]
- contentful.swift version number: 4.2.1
- Xcode version number: 10.1
- Target operating system(s) and version number(s)
  - [x] iOS: 9.0.0
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [x] Carthage
  - [ ] Cocoapods

Initializing a Client using:
`let client = Client(spaceId: "xxxxxx", accessToken: "yyyyy")`
causes the application to crash. This occurs on the both the simulator as well as on device.
The error does not occur when using version 4.2.0

**Comment by loudmouth** [comment]
Hi there, thanks for the report. Can you please provide the crash output? With the current information, it's hard to verify there is any issue.

Secondly, if there is a fix in an upstream version that does not contain any breaking changes, is there any reason we should leave this issue open?

**Comment by ericDMH** [comment]
Hello @loudmouth :
I'm really sorry, the issue can be closed. Actually the crash occurred due to the fact that one of our dependencies used a version of Contenful.swift that had not been updated yet. Updating it to 4.2.1. solved the problem.

Thanks for the prompt response

**Comment by ericDMH** [comment]
closed

**Comment by loudmouth** [comment]
No problem @ericDMH !

Have a good one ;-)
