### ISSUE TITLE
Content Management SDK for Swift

### ISSUE THREAD

**Issue by Will16** [contentful/contentful.swift#258]
Hi,

In previous projects, I've been using the deprecated Objective-C Contentful Management API to post and update content from the iOS app. I've read in a July 2017 post on this forum that a Swift version of this SDK "is on the roadmap, but probably won't be published for at least several more months.".
Will this SDK be released soon? And meanwhile, to post content, do you still suggest using the deprecated Objective-C SDK as a starting point and fork it to modify it if necessary? Or do you suggest developers make their own classes to make direct calls to the API instead? 

Thanks for your help!
Will

**Comment by matelo** [comment]
there is already Swift SDK, closing

**Comment by loudmouth** [comment]
This SDK is only for the Content Delivery and Preview APIs. Not for the [Content Management API](https://www.contentful.com/developers/docs/references/content-management-api/)

If there is a new SDK, maybe it could be linked here?
