### ISSUE TITLE
Recursive infinity loop on decoding of nested arrays in arrays

### ISSUE THREAD

**Issue by THaui** [contentful/contentful.swift#260]
- contentful.swift version number: 4.1.3
- Xcode version number: 10.1
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods

Hi Contentful team,
I've found an issue on decoding arrays of arrays [[1,2], [1,2]] if it's set as value of a field.
It's located in Decodable.swift at line 311:
`} else if let nestedArray = try? decode(Array<Any>.self) {`
If the current container is an array it will call decode(...) recursively on the same container what will end in an infinity loop. 
`decode` must be called on the `self.nestedUnkeyedContainer()` like it's done with the dictionary case, to solve this issue.

Best regards and thanks.

**Comment by leoneparise** [comment]
Solved in PR: https://github.com/contentful/contentful.swift/pull/262
