### ISSUE TITLE
Support swift 5.0

### ISSUE THREAD

**Issue by TomVanDerSpek** [contentful/contentful.swift#263]
When are you planning to release an update for Swift 5.0?

**Comment by kaleemasadmughal** [comment]
I am also waiting.

**Comment by leoneparise** [comment]
Hi @TomVanDerSpek, we have plans to release an update for Swift 5.0 pretty soon. It's already in our roadmap. :)

**Comment by leoneparise** [comment]
Hi @TomVanDerSpek there is a PR https://github.com/contentful/contentful.swift/pull/265 to support Swift 5.0 waiting to be merged. :)

**Comment by TomVanDerSpek** [comment]
Thanks for keeping me posted :)

**Comment by TomVanDerSpek** [comment]
@leoneparise Any update on this?

**Comment by andrewcampoli** [comment]
@leoneparise Could we get an update on this? Would love to be able to continue using Contentful!

**Comment by leoneparise** [comment]
Hey guys, I was working for Contentful at the time but I don't have contact with the team anymore. Try to get in touch with other contributors like @loudmouth to know when they can merge the PR.

**Comment by andrewcampoli** [comment]
Thanks for the update @leoneparise!

**Comment by loudmouth** [comment]
Hey all, as of 2019, I am also no longer part of the Contentful team. As much as I wish I could help, I can't do anything here either. Good luck :-)

**Comment by andrewcampoli** [comment]
I appreciate the update @loudmouth, I'm starting to worry this project is dead.

**Comment by Killectro** [comment]
Hey everyone! I saw that the PR had been landed but we are manually including the `.framework` into our project so we sadly can't upgrade until a new release is cut. Does anyone know when this might happen?

Thanks

**Comment by Khaledgarbaya** [comment]
Hey folks,
There is a PR already https://github.com/contentful/contentful.swift/pull/269 and it's merged we'll be releasing Swift 5 support soon

**Comment by manmal** [comment]
As per 4e812b29d7fb4d794584376599ff87e3998fd42c, Swift 5.0 is officially supported, with version `5.0.0`.
If you use Cocoapods, please do a `pod repo update master` before doing `pod install` or `pod update`.
