### ISSUE TITLE
Support swift 5.1

### ISSUE THREAD

**Issue by Wouter125** [contentful/contentful.swift#275]
- contentful.swift version number: 5.0.0
- Xcode version number: 11.0 beta (11M336w)
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [x] Carthage
  - [ ] Cocoapods

The latest version of the contentful library as build by carthage is not supporting the latest swift version. Therefor my project won't compile. So can we do a quick build with Swift 5.1 so I can run it on iOS 13?

It's throwing the following issue to be precise;

```Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/wouter/Documents/Sideprojects/Code/Foreignrap/Foreignrap 2.0/Foreignrap/Carthage/Build/iOS/Contentful.framework/Modules/Contentful.swiftmodule/arm64.swiftmodule```

Can we do a quick update? Or should I build the module myself and wait for the carthage one to be updated?

**Comment by Wouter125** [comment]
Okay, build it myself, and works :)

**Comment by Killectro** [comment]
@Wouter125 what did you do to build it yourself? Do you have a set of commands? Would help me and probably other developers in the future as well.

**Comment by Wouter125** [comment]
I just cloned the repo, build the framework, grabbed the framework from the build and inserted it into my project. iOS13 was still in beta, so the master branch isn't supporting that yet, which makes sense. 

I was just preparing my app for it, so integrated it this way to do some quick testing. When iOS13 is publicly available, this repo will probably update as well to support Swift 5.1

**Comment by Killectro** [comment]
Thanks @Wouter125!
