### ISSUE TITLE
Swift version in 5.0.0 CocoaPods spec specifies version "4.2"

### ISSUE THREAD

**Issue by joshuafinch** [contentful/contentful.swift#278]
- contentful.swift version number:  5.0.0
- Xcode version number: 10.2
- Target operating system(s) and version number(s)
  - [x] iOS: 10.3
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods

Would be good if the podspec specifies using version 5.0 of Swift instead of version 4.2
Alternatively, the `swift_versions` key can be used to show support for both version 4.2 and 5.0 of swift (with CocoaPods 1.7 and above)

**Comment by matelo** [comment]
waiting for PR: https://github.com/contentful/contentful.swift/pull/290

**Comment by matelo** [comment]
fixed in version 5.0.6
