### ISSUE TITLE
4.x.x -> 5.x.x migration?

### ISSUE THREAD

**Issue by timqzm** [contentful/contentful.swift#282]
Could you complete Migrations.md with 4>5 migration guide?

**Comment by bhadreshnp** [comment]
same here. can't upgrade in Xcode 11.
very bad support and worst maintenance.
I'll remove this library from my project down the line.

**Comment by timqzm** [comment]
@bhadreshnp just a guess: make sure your project language is Swift 5 to use Contentful 5

**Comment by bhadreshnp** [comment]
Yeah I've selected swift 5 of course and Xcode 11 gives pre-selected swift 5 as language.

**Comment by bhadreshnp** [comment]
Getting error as below,
```*** Fetching contentful.swift
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/contentful/contentful.swift.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/bhadresh/Library/Caches/org.carthage.CarthageKit/dependencies/contentful.swift)) failed with exit code 1
```

**Comment by timqzm** [comment]
Probably it's about Carthage setup. I use CocoaPods and now it seems fine

**Comment by matelo** [comment]
@bhadreshnp can you please be more specific about how to reproduce this issue? I have tested migration with CocoaPods as well as with Carthage, but both of them worked without error.

**Comment by matelo** [comment]
not able to reproduce this issue
