### ISSUE TITLE
Unable to filter by link reference ID

### ISSUE THREAD

**Issue by hikui** [contentful/contentful.swift#284]
- contentful.swift version number: 5.0.5
- Xcode version number: 10.3
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods

It looks like the SDK is unable to filter content by its link reference's ID. 

Suppose I have two content models, `Product` and `Category`. A product has a field `category` which is of type `Category`. In the app, I stored some category IDs, and I want to get products under these categories.

Here's the code I tried:

```swift
let categoryIds = [...]
let categoryConstraints = LinkQuery<Category>.where(sys: Sys.CodingKeys.id, .includes(categoryIds))

var query = QueryOn<Product>
                .include(1)
                .where(linkAtField: .category, matches: categoryConstraints)
```

However, the query simply drops the ID constraint when generating the URL.

By looking into the code, I found `.where(sys: _ operation:)` exists in the AbstractQuery.

```swift
static func `where`(sys key: Sys.CodingKeys, _ operation: Query.Operation) -> Self {
    return Self.where(valueAtKeyPath: "sys.\(key.stringValue)", operation)
}

static func `where`(valueAtKeyPath keyPath: String, _ operation: Query.Operation) -> Self {
    let parameter = keyPath + operation.string

    let query = Self()
    query.parameters[parameter] = operation.values

    return query
}
```

The code above doesn't set LinkQuery's `propertyName` which is required by `QueryOn`'s `where(linkAtField:matches:)`:

```swift
public func `where`<LinkType>(linkAtField fieldsKey: EntryType.FieldKeys,
                                                    matches linkQuery: LinkQuery<LinkType>) -> QueryOn<EntryType> {

    parameters["fields.\(fieldsKey.stringValue).sys.contentType.sys.id"] = LinkType.contentTypeId

    // If propertyName isn't unrwrapped, the string isn't constructed correctly for some reason.
    if let propertyName = linkQuery.propertyName {
        let filterParameterName = "fields.\(fieldsKey.stringValue).\(propertyName)\(linkQuery.operation.string)"
        parameters[filterParameterName] = linkQuery.operation.values
    }
    return self
}
``` 

You can see here, the `propertyName` will be nil and the ID constraints will be dropped.

**Comment by matelo** [comment]
Hello @hikui 
I am not sure if I understand the issue correctly, but I think that similar situation happens in our example project. Please take a look at `CourseViewController` how the query is build:
`func query(slug: String) -> QueryOn<Course>`

**Comment by hikui** [comment]
Hi @matelo 

The example query you pointed out isn't querying a model by one of its reference, instead, it's querying on a field of a model.

The problem I found happens in the situation when you query a model by one of its linked references (foreign key). 

For example, there are two models, `Product` and `Category`, a product belongs to a category.  

```
+---------+     +--------+
| Product |  +->+Category|
+---------+  |  +--------+
|*category+--+
+---------+

```

Now I want to query all products that belong to a category. Before that, I already know the category's `id`. So I want to query "all products whose category's Id equals to xyz"

According to your documentation, the query should look like

```swift
let categoryIds = [...]
let categoryConstraints = LinkQuery<Category>.where(sys: Sys.CodingKeys.id, .includes(categoryIds))

var query = QueryOn<Product>
                .include(1)
                .where(linkAtField: .category, matches: categoryConstraints)
```

But this query doesn't work at all. The reason why it's not working is explained in the issue.

Actually I've created [a patch](https://github.com/hikui/contentful.swift/commit/5c40115492b0c0f1ee9092e7e4526287fd446ae5) to solve the problem and it is used in our project.

**Comment by matelo** [comment]
hi @hikui 
thanks for explanation and for the patch. I will check it and possibly merge it in upcoming release
