### ISSUE TITLE
Add Swift 5.1 support

### ISSUE THREAD

**Issue by Killectro** [contentful/contentful.swift#285]
- contentful.swift version number: 5.0.0
- Xcode version number: Xcode 11
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods

There is currently no support for Swift 5.1. I would really appreciate a new version of the SDK built with the latest versions of the compiler! Another user pulled down and built it manually but I don't think that's the greatest developer workflow in the long run.

**Comment by andrewcampoli** [comment]
Bump

**Comment by matelo** [comment]
can you please check this on latest release 5.0.7?

**Comment by matelo** [comment]
fixed
