### ISSUE TITLE
Contentful SDK adds CoreLocation.framework to `Link Binary With Libraries`

### ISSUE THREAD

**Issue by marcin-bo** [contentful/contentful.swift#287]
- contentful.swift version number: 4.1.3 and latest
- Xcode version number: 10.2.1
- Target operating system(s) and version number(s)
  - [x] iOS: 11.0
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods: 1.6.1

I think Contentful SDK does not use CoreLocation.framework but it links it in `Link Binary With Libraries` when using Cocoapods - see the attached screenshot:
<img width="1044" alt="screen" src="https://user-images.githubusercontent.com/26303487/67752525-6964ca80-fa33-11e9-9eb8-be077ecbd9ca.png">

As a result it is required to add `NSBluetoothPeripheralUsageDescription` and `NSBluetoothAlwaysUsageDescription` properties to your Info.plists file (because you have CoreLocation.framework in your app, that's a new requirement).

**Comment by matelo** [comment]
waiting for PR: https://github.com/contentful/contentful.swift/pull/290

**Comment by matelo** [comment]
fixed in version 5.0.6
