### ISSUE TITLE
Is resolveLink an asynchronous call?

### ISSUE THREAD

**Issue by basememara** [contentful/contentful.swift#296]
I'm trying to map my Contentful objects to a struct, but sometimes the reference fields are `nil`. Is this because the below decoding is asynchronous?

```swift
try fields.resolveLink(forKey: .someLink, decoder: decoder) { [weak self] in
    self?.someLink = $0 as? SomeContentfulObject
}
```

How does the object tree get constructed, is there a way to know when it has been completed so I can map them to `structs`?

**Comment by matelo** [comment]
Yes, it is async. 
To see how it can be used, please refer to Example app, for example struct `Course`

**Comment by basememara** [comment]
Just some feedback about the example project, it is quite complex to show the usage of Contentful. Theres several irrelevant dependencies that just cloud how to use Contentful.. like why Fabric, Snowplow, etc. And the structure is very opinionated to know how to use Contentful in an iOS app. I did look at it tho but I think confused me more.

As far as an async call to populate the fields of the object, is it dangerous that an object doesn't get "fully" initialized since it can be used throughout the app before it's ready? The async resolve seems like a workaround to fill in the field values after initialization since the response from Contentful give you the entire tree you need to decode into your own types, so why the deferred values? If it's for performance, is there a way to normalize the response so we only get the ID's of the child entries and make a second call on the detail screens... but I don't think including 3 or 4 levels deep is a problem for Contentful.

I was looking at the source code and was wondering why you couldn't do something like: `func resolve<T>(_ link: Link) -> T?`. I understand you're trying to avoid duplicates and such, but its all done in the background queue so a few milliseconds extra to finish decoding would be a big win for a "fully" initialized object and would allow us to use immutable structs natively from Contentful.

I realize I must be over-simplifying things and missing something, but can you share exactly in the SDK code what is preventing making the decoder synchronous? Shouldn't `DataCache` have everything it needs to avoid duplicate objects and deserialization?

**Comment by basememara** [comment]
I'm attached a video below illustrating the race conditions that come with non-fully initialized objects from Contentful. As I pull to refresh, the cache shows its getting asset and linked properties inconsistently. This is because as we send Contentful objects through our layers, they are not really done initializing.

![ezgif-6-4c681f6f00ba](https://user-images.githubusercontent.com/892152/80959965-df2c6300-8dd5-11ea-92b3-2198afe99001.gif)

**Comment by obianachebe** [comment]
I also need to be able to resolve links synchronously as my project requires immutability. As far as I can tell, I don't see why links must be resolved async since `heterogenousIncludes` and `homogeneousIncludes` are serialized before the items with links that reference them are. 

I forked the lib and this solution is working fine for me:

```
func resolveLink<E>(forKey key: KeyedDecodingContainer.Key, decoder: Decoder) throws -> E? {
    guard decoder.canResolveLinks  else { return nil }
    let linkResolver = decoder.linkResolver
    if let link = try decodeIfPresent(Link.self, forKey: key) {
        let linkKey = DataCache.cacheKey(for: link)
        return linkResolver.dataCache.item(for: linkKey) as? E
    } else {
        return nil
    }
}

func resolveLinksArray<E>(forKey key: KeyedDecodingContainer.Key, decoder: Decoder) throws -> [E]? {
    guard decoder.canResolveLinks  else { return nil }
    let linkResolver = decoder.linkResolver
    if let links = try decodeIfPresent(Array<Link>.self, forKey: key) {
        let linkKey: String = links.reduce(into: LinkResolver.linksArrayPrefix) { id, link in
            id += "," + DataCache.cacheKey(for: link)
        }
        let firstKeyIndex = linkKey.index(linkKey.startIndex, offsetBy: LinkResolver.linksArrayPrefix.count)
        let onlyKeysString = linkKey[firstKeyIndex ..< linkKey.endIndex]
        // Split creates a [Substring] array, but we need [String] to index the cache
        let keys = onlyKeysString.split(separator: ",").map { String($0) }
        return keys.compactMap { linkResolver.dataCache.item(for: $0) } as? [E]
    } else {
        return nil
    }
}
```

Are there any potential drawbacks to not resolving links async?

**Comment by obianachebe** [comment]
This doesn't seem to be a valid solution for responses with includes > 1. I'll 

> I also need to be able to resolve links synchronously as my project requires immutability. As far as I can tell, I don't see why links must be resolved async since `heterogenousIncludes` and `homogeneousIncludes` are serialized before the items with links that reference them are.
> 
> I forked the lib and this solution is working fine for me:
> 
> ```
> func resolveLink<E>(forKey key: KeyedDecodingContainer.Key, decoder: Decoder) throws -> E? {
>     guard decoder.canResolveLinks  else { return nil }
>     let linkResolver = decoder.linkResolver
>     if let link = try decodeIfPresent(Link.self, forKey: key) {
>         let linkKey = DataCache.cacheKey(for: link)
>         return linkResolver.dataCache.item(for: linkKey) as? E
>     } else {
>         return nil
>     }
> }
> 
> func resolveLinksArray<E>(forKey key: KeyedDecodingContainer.Key, decoder: Decoder) throws -> [E]? {
>     guard decoder.canResolveLinks  else { return nil }
>     let linkResolver = decoder.linkResolver
>     if let links = try decodeIfPresent(Array<Link>.self, forKey: key) {
>         let linkKey: String = links.reduce(into: LinkResolver.linksArrayPrefix) { id, link in
>             id += "," + DataCache.cacheKey(for: link)
>         }
>         let firstKeyIndex = linkKey.index(linkKey.startIndex, offsetBy: LinkResolver.linksArrayPrefix.count)
>         let onlyKeysString = linkKey[firstKeyIndex ..< linkKey.endIndex]
>         // Split creates a [Substring] array, but we need [String] to index the cache
>         let keys = onlyKeysString.split(separator: ",").map { String($0) }
>         return keys.compactMap { linkResolver.dataCache.item(for: $0) } as? [E]
>     } else {
>         return nil
>     }
> }
> ```
> 
> Are there any potential drawbacks to not resolving links async?
> 
> EDIT:
> 
> Here's my implementation:
> [obianachebe@7a5fa67](https://github.com/obianachebe/contentful.swift/commit/7a5fa67c71b63eba5cd8d98265543978fb04c46f)

This doesn't seem to be a valid solution when includeLevel > 1. I ended up using RxSwift to ensure my models were fully resolved downstream.

**Comment by tomkowz** [comment]
I did take a look at how the resolving logic works at the moment and for now, as the library is using the `Decodable` protocol for decoding objects this is not easy to add "synchronicity" to the code. Indeed it would be nice to not have callbacks in constructors when accessing some model's data from the network and use `struct` instead of `class` but with the current implementation it is a difficult goal – however I'll take another look on that.

In terms of not fully initialized objects, I noticed that the `churnLinks` method is being called too fast sometimes as it does not wait for the `resolveLink` or `resolveLinksArray` to finish. So, we've got a race here. Not good. 

I came up with an idea that if we cannot make it all synchronous without the callbacks (for the time being) let's fix the `churnLinks` method to report the completeness of the work when it is really complete, not when the `HomogenousArrayResponse` or `HeterogenousArrayResponse` did finish its synchronous-part of decoding and call the `churnLinks`, because there is still some async work ongoing. 

I noticed another kind of issue when reading through the code but this is the most important to be fixed at the moment I believe.

So the fix would be like this:
1) `Client.fetch(url:then:)` is called by the user.
2) `Client.handleJSON(data:completion)` is called after the successful fetch.
3) `LinkResolver.perform(decoding:completion:)` is called right away.
4) `*ArrayResponse` decodes its content as usual but does not call the `churnLinks` after the synchronous work is done as it was done before.
5) `LinkResolver` calls `churnLinks` (itself) right after synchronous work is done in step 4.
6) When all the `LinkResolver.callbacks` are executed and removed then the `LinkResolver` itself calls the completion of the link resolving process - not earlier, not later.
7) Callback of `Client.fetch(url:then:)` is called when all your models are fully instantiated.

What you think guys?

Here is the PR I've created for the Support Team review: https://github.com/contentful/contentful.swift/pull/304

**Comment by tomkowz** [comment]
Closing the issue as there is no more discussion and the PR has been merged.

**Comment by Castle2107** [comment]
Hey @tomkowz, is there any update on this? I'm facing the same issue, using the latest SDK version. 

Is there an example of a way that implements the pseudo code you added in your last comment before closing this issue? Or could you provide a more descriptive code example?

**Comment by Castle2107** [comment]
Maybe @obianachebe, @basememara, could you share your solution to this problem using RxSwift, please?

**Comment by obianachebe** [comment]
@Castle2107 I ended up changing my Contentful object models to classes as it was too difficult to make it work with structs + RxSwift. 

If you don't need those objects to be structs, it's just easier to work with the library as is.

**Comment by Castle2107** [comment]
@obianachebe, that's the thing I don't understand, all my Contentful models are classes. This is pretty much my implementation:

**Rx-swift function implementation**
```
func getMainModel() -> Driver<Result<MainModel, Error>> {
      return Driver.create({ observer -> Disposable in
            let client = Client()            
            let query = QueryOn<MainModel>
                .where(sys: .id, .equals("id"))
                .include(10)
            
            client.fetchArray(of: MainModel.self, matching: query) { (result) in
                switch result {
                case .success(let response):
                    guard let item = response.items.first else {
                        observer.onNext(
                            .failure(GenericError.empty)
                        )
                        observer.onCompleted()
                        return
                    }
                    observer.onNext(
                        .success(item)
                    )
                    observer.onCompleted()
                case .failure(let error):
                    observer.onNext(.failure(error))
                    observer.onCompleted()
                }
            }
            return Disposables.create()
        })
}
```

**Main Model**
```
public class MainModel: EntryDecodable, FieldKeysQueryable {
    public static let contentTypeId = "mainModel"
    
    public var contentBlocks = [ContentType]()
    
    required public init(from decoder: Decoder) throws {
        let container = try decoder.contentfulFieldsContainer(keyedBy: MainModel.FieldKeys.self)
        
        try container.resolveLinksArray(forKey: .contentBlocks, decoder: decoder, callback: { [weak self] in
            guard let blocks = $0 as? [AnyObject] else {
                return
            }
            // mapping Contentful Objects
            self?.contentBlocks = blocks.compactMap({ ContentType(contentType: $0) })
        })
    }
    
    public enum FieldKeys: String, CodingKey {
        case contentBlocks
    }
}
```

**Nested Model**
```
public class ModelA: EntryDecodable, FieldKeysQueryable {
    public static let contentTypeId = "modelA"
    
    public var anotherModel = [AnotherContentfulModel]()
    
    required public init(from decoder: Decoder) throws {
        let container = try decoder.contentfulFieldsContainer(keyedBy: MainModel.FieldKeys.self)
        
        try container.resolveLink(forKey: .contentBlocks, decoder: decoder, callback: { [weak self] in
            self?.anotherModel = $0 as? AnotherContentfulModel
        })
    }
}
```

```
public enum ContentType: Equatable {
    case a(content: InMemoryModelA)
    case b(content: InMemoryModelB)
    case c(content: InMemoryModelC)

    init?(contentType: AnyObject) {
        switch contentType {
        case let modelA as ModelA:
            let content = modelA.mappedToMemory()
            self = .a(content: content)
            
        case let modelB as ModelB:
            let content = modelB.mappedToMemory()
            self = .b(content: content)
        
        case let modelC as ModelC:
            let content = modelC.mappedToMemory()
            self = .c(content: content)
        
        default:
            return nil
        }
    }
}
```

Am I doing something wrong?
