### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by dcilia** [contentful/contentful.swift#3]
A friendly request to add Carthage support (build into a framework)

**Comment by neonichu** [comment]
Yep, this will happen soon once we're shipping 1.0

**Comment by dcilia** [comment]
awesome, thanks.

**Comment by neonichu** [comment]
The latest release has a binary build for Carthage attached: https://github.com/contentful/contentful.swift/releases/edit/0.2.0

**Comment by woxtu** [comment]
Hi,

I tried to add contentful.swift to my project using Carthage, and I got the following runtime error. How I can fix it?
```
dyld: Library not loaded: @rpath/Clock.framework/Clock
  Referenced from: ***/Contentful.framework/Contentful
  Reason: image not found
```
FYI, I wrote Cartfile as follows:
```
github "contentful/contentful.swift" ~> 0.2
```
Carthage 0.16.2, Xcode 7.3

**Comment by neonichu** [comment]
Thanks for reporting, I'll look into fixing this in the coming days.

**Comment by neonichu** [comment]
I somehow expected that `carthage archive` would also archive the dependencies and did not actually test this in an example app. Have now added a `Cartfile` and properly tested this with:

```
github "contentful/contentful.swift" ~> 0.2.1
```

**Comment by woxtu** [comment]
It worked! Thank you.

**Comment by woxtu** [comment]
Just one more thing. contentful.swift requires iOS 9.0+ now. Is this correct? My Deployment Target is 8.1, so it's not good for me...

**Comment by neonichu** [comment]
Thanks for noticing, that was configured wrong in the Xcode project, I have updated the build for version 0.2.1 with one that has 8.0 deployment target.

**Comment by woxtu** [comment]
That's good, thanks again.
