### ISSUE TITLE
sys.updatedAt always returns nil when requesting it

### ISSUE THREAD

**Issue by jlorfeo** [contentful/contentful.swift#300]
Hey everybody,

when trying to access the Sys property "updatedAt" after an entry was fetched it always returns nil.
This seems happening due to an unsuccessful parsing of the date in the sdk. The same thing happens to "createdAt".

- contentful.swift version number: 5.0.9
- Xcode version number: 11.3.1
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods

**Comment by tomkowz** [comment]
I tried in on my side with 5.0.9 and the newest version of the lib and it seems to work for me. Did you maybe change the `dateDecodingStrategy` in the `ClientConfiguration`? For the default date decoding strategy it works for me every time.

**Comment by tomkowz** [comment]
Didn't get answer for several days now. Closing the issue. If something similar happened again please open a new issue.
