### ISSUE TITLE
Xcode11 Package Resolution Failed

### ISSUE THREAD

**Issue by 1922353531** [contentful/contentful.swift#301]
When I used swift package manager in Xcode11(Swift5) to fetch the contentful.swift, I got can't fetch it and the error is:

Showing All Messages
: terminated(1): SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.vyJg2Cm4TR/Listeners GIT_SSH_COMMAND=ssh -oBatchMode=yes USER=tony TMPDIR=/var/folders/jv/t1k0tf9s5pg3qyclhl3lq4w40000gn/T/ SHELL=/bin/zsh XPC_FLAGS=0x0 MallocNanoZone=0 CA_ASSERT_MAIN_THREAD_TRANSACTIONS=1 CA_DEBUG_TRANSACTIONS=1 __CF_USER_TEXT_ENCODING=0x1F5:0x19:0x34 HOME=/Users/tony PATH=/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin XPC_SERVICE_NAME=com.apple.dt.Xcode.13664 GIT_TERMINAL_PROMPT=0 LOGNAME=tony /Applications/Xcode.app/Contents/Developer/usr/bin/git -C /Users/tony/Library/Developer/Xcode/DerivedData/DesignCode-bufrzqfvclstzxdqmlurzkzsybur/SourcePackages/checkouts/contentful.swift submodule update --init --recursive output:
    Submodule 'Carthage/Checkouts/DVR' (https://github.com/venmo/DVR.git) registered for path 'Carthage/Checkouts/DVR'
    Submodule 'Carthage/Checkouts/OHHTTPStubs' (https://github.com/AliSoftware/OHHTTPStubs.git) registered for path 'Carthage/Checkouts/OHHTTPStubs'
    Cloning into '/Users/tony/Library/Developer/Xcode/DerivedData/DesignCode-bufrzqfvclstzxdqmlurzkzsybur/SourcePackages/checkouts/contentful.swift/Carthage/Checkouts/DVR'...
    fatal: unable to access 'https://github.com/venmo/DVR.git/': Failed to connect to 127.0.0.1 port 1087: Connection refused
    fatal: clone of 'https://github.com/venmo/DVR.git' into submodule path '/Users/tony/Library/Developer/Xcode/DerivedData/DesignCode-bufrzqfvclstzxdqmlurzkzsybur/SourcePackages/checkouts/contentful.swift/Carthage/Checkouts/DVR' failed
    Failed to clone 'Carthage/Checkouts/DVR'. Retry scheduled
    Cloning into '/Users/tony/Library/Developer/Xcode/DerivedData/DesignCode-bufrzqfvclstzxdqmlurzkzsybur/SourcePackages/checkouts/contentful.swift/Carthage/Checkouts/OHHTTPStubs'...
    fatal: unable to access 'https://github.com/AliSoftware/OHHTTPStubs.git/': Failed to connect to 127.0.0.1 port 1087: Connection refused
    fatal: clone of 'https://github.com/AliSoftware/OHHTTPStubs.git' into submodule path '/Users/tony/Library/Developer/Xcode/DerivedData/DesignCode-bufrzqfvclstzxdqmlurzkzsybur/SourcePackages/checkouts/contentful.swift/Carthage/Checkouts/OHHTTPStubs' failed
    Failed to clone 'Carthage/Checkouts/OHHTTPStubs'. Retry scheduled
    Cloning into '/Users/tony/Library/Developer/Xcode/DerivedData/DesignCode-bufrzqfvclstzxdqmlurzkzsybur/SourcePackages/checkouts/contentful.swift/Carthage/Checkouts/DVR'...
    fatal: unable to access 'https://github.com/venmo/DVR.git/': Failed to connect to 127.0.0.1 port 1087: Connection refused
    fatal: clone of 'https://github.com/venmo/DVR.git' into submodule path '/Users/tony/Library/Developer/Xcode/DerivedData/DesignCode-bufrzqfvclstzxdqmlurzkzsybur/SourcePackages/checkouts/contentful.swift/Carthage/Checkouts/DVR' failed
    Failed to clone 'Carthage/Checkouts/DVR' a second time, aborting
  But when I use another package dependence, it works. Could you help me?

**Comment by tomkowz** [comment]
Thanks for reporting the issue! I am about to update the DVR library which should fix the problem.

**Comment by tomkowz** [comment]
This has been fixed in #303.
