### ISSUE TITLE
Breaking change from 5.0.11 to 5.0.12

### ISSUE THREAD

**Issue by superarts** [contentful/contentful.swift#308]
- contentful.swift version number: `5.0.12`
- Xcode version number: `11.3`
- Target operating system(s) and version number(s)
  - [x] iOS: 13.3
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [ ] Cocoapods `1.9.3`

We've updated from 5.0.11 to 5.0.12, and found that the project couldn't be built due to the removal of the bundled `Result.swift`; while getting rid of `Contentful.Result` is a good chance, it's indeed a breaking chance so version number should be bumped to `5.1.x`.

**Comment by tomkowz** [comment]
@superarts Thank you for your report. Indeed we should bump the version to 5.1.0. PR has been created.
