### ISSUE TITLE
Compiler warning in `Field.swift` file

### ISSUE THREAD

**Issue by renamari** [contentful/contentful.swift#315]
- contentful.swift version number: 5.1.2
- Xcode version number: 11.6
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods

Our company's iOS CI/CD process currently uses `xcodebuild` with these two flags: `"SWIFT_TREAT_WARNINGS_AS_ERRORS=YES" "GCC_TREAT_WARNINGS_AS_ERRORS=YES", so we started getting build errors when integrating this into our project.

There seems to be this warning in the Contentful framework on `Field.swift` (line 92):

```
self.itemType = FieldType(rawValue: itemTypeString ?? FieldType.none.rawValue) ?? .none // Assuming you mean 'Optional<FieldType>.none'; did you mean 'FieldType.none' instead?
```

Because itemType is defined as an optional property, the compiler gets confused. 

My suggestion is to update the line above to:

```
self.itemType = FieldType(rawValue: itemTypeString ?? FieldType.none.rawValue) ?? FieldType.none
```

This will not only get rid of the warning, but also provide a bit more clarity :) 

Thanks for the awesome tools!

**Comment by tomkowz** [comment]
@renamari Thanks for reporting that!
