### ISSUE TITLE
resolveLinksArray returns array of NSNulls

### ISSUE THREAD

**Issue by pzmudzinski** [contentful/contentful.swift#329]
- contentful.swift version number: 5.4.1
- Xcode version number: 12.3
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods

I've got entry with one-to-many array of some other entries. Trying to decode it like that:
```swift
try fields.resolveLinksArray(forKey: .possibleAnswers, decoder: decoder) { [weak self] answers in ... }
```

I've registered both types of entries in `contentTypeClasses`, I've got the same code working for other entries but for some reason one specific type causes this issue (it's not even reaching constructor) - it shows correct number of entries but all of them are `NSNull` without *any* error message or explanation what's going on:
![image](https://user-images.githubusercontent.com/1887653/104318244-6bebfc80-54df-11eb-8e9d-23094f4dbc8a.png)

What could be causing that? How are we supposed to debug any decoding issues? Why it isn't giving any information what could be an issue?

In addition if I try to fetch one record of that type everything works:
```swift
client.fetch(typeOfPossibleAnswers, id: "...") { result in
                print("result \(result)") // success! 
            }
```

**Comment by pzmudzinski** [comment]
One thing to add is the structure is like that:
there is entity `A`, which has array of entities `B`, and each entity B has another array of entities `C`. 
If I fetch entity `B` - it works and I see it decodes array of entities `C`. 
If I fetch entity `A`, it decodes entities B but it does not reach to decoding any of `C`. 

Does this SDK does not support nested links at depth 2?

**Comment by pzmudzinski** [comment]
Ok after digging into the code I think I've found `Query.include` method which manages "depth" of that fetch. 
So solution was to use `myQuery.include(3)`. 

I think this is something which should be added to Readme - I couldn't find any info on that and default behavior with`NSNull`s seems to be weird.

**Comment by mariuskurgonas** [comment]
Hey @pzmudzinski ,

Thanks you for the feedback and great that in the end you found the solution. I will make sure this is added to the documentation going forwards. 

I will also look into why does it return the array of nulls in case the depth level is not specified. I think i generally understood your use case and setup with arrays within arrays. Would you be able to share a simple working example of the code that would help me see the complete picture of your setup and help me in reproducing exactly the way you tried it?

**Comment by marius-se** [comment]
I had the exact same issues. The `Query.include` really helped me a lot. Thanks @pzmudzinski for pointing that out! What is interesting: If the key is representing an Asset value, everything works just fine. Is there a reason for that? Let's say I have:

-locations: Location
--facilities: [Facility]
---address: Address
---image: Asset

Without specifying the `Query.include` the image property will be resolved while the address won't.

**Comment by pzmudzinski** [comment]
@marius-se It took me like 5 hours to figure it out so appreciate your comment 😂
@mariuskurgonas  nothing fancy, just use `Client` and do an query for entity with nested arrays, just like in my A-B-C example

**Comment by leonardopantaleao** [comment]
I hope I can save someone else's time:
EntryType = the class type you're struggling to get the array with arrays
let query = QueryOn<EntryType>.include(3)
client.fetchArray(of: EntryType.self, matching: query) { response in 
...
