### ISSUE TITLE
func handleJSON can call two failure completions

### ISSUE THREAD

**Issue by timqzm** [contentful/contentful.swift#330]
Seems like a typo. Probably, `return` is missed after line 476.

**Comment by mariuskurgonas** [comment]
@timqzm 

Thanks for catching this. Simple return will not do the trick because of then skipping `churnLinks()` call later. I will see about putting second half of the function into the `do` block and remove some of the fail completions as redundant.

**Comment by mariuskatcontentful** [comment]
Resolved
