### ISSUE TITLE
Xcode 12 build warnings because Contentful.podspec is still using iOS8

### ISSUE THREAD

**Issue by lepolt** [contentful/contentful.swift#331]
- contentful.swift version number: 5.1.2
- Xcode version number: 12.5 Beta
- Target operating system(s) and version number(s)
  - [x] iOS: 13+
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [x] Cocoapods
  - [ ] Carthage

Building my project is causing a warning with Contentful because the Contentful.podspec file is still deploying to iOS8: 
`spec.ios.deployment_target     = '8.0'`

Are there plans to update? Would a PR help move this issue along? Thanks!

**Comment by mariuskatcontentful** [comment]
Resolved
