### ISSUE TITLE
Initial data sync with Contentful in iOS takes more time when compare with Andoid

### ISSUE THREAD

**Issue by ZVKYVaradharaj** [contentful/contentful.swift#338]
- contentful.swift version number: 
- Xcode version number: 12.4
- Target operating system(s) and version number(s)
  - [x] iOS: 
  - [ ] tvOS: 
  - [ ] watchOS:
  - [ ] macOS:
- Package manager:
  - [ ] Carthage
  - [x] Cocoapods

Hi, we are using "client.sync" function for the initial sync to SQLite DB, It takes around 20 mins to sync 2 to 3 MB of data even with network speed is around 200 MB/s. The same data in Android it syncs within 5 to 10 seconds. Only in iOS, it takes a huge time.  We are loosing Clients because of this.

iOS data sync with Contentful is 30 times slower than Android.

**Comment by marcin-bo** [comment]
Hi, 

Our users also experience slow synchronization with Contentful. We use:
- Contentful 5.4.1
- ContentfulPersistenceSwift 0.17.4

On simulator in a debug enviromnent the synchronization seems to be quicker than on devices.

**Comment by ZVKYVaradharaj** [comment]
> * contentful.swift version number:
> * Xcode version number: 12.4
> * Target operating system(s) and version number(s)
>   
>   * [x]  iOS:
>   * [ ]  tvOS:
>   * [ ]  watchOS:
>   * [ ]  macOS:
> * Package manager:
>   
>   * [ ]  Carthage
>   * [x]  Cocoapods
> 
> Hi, we are using "client.sync" function for the initial sync to SQLite DB, It takes around 20 mins to sync 2 to 3 MB of data even with network speed is around 200 MB/s. The same data in Android it syncs within 5 to 10 seconds. Only in iOS, it takes a huge time. We are loosing Clients because of this.
> 
> iOS data sync with Contentful is 30 times slower than Android.

Hi Contentful team, Any update on this bug which create lot of issue in our product.

**Comment by mobbie** [comment]
Same here - is there any solution for that? It seems the core data handling slows it down to the level of no-go.

**Comment by mariuskatcontentful** [comment]
Should more or less match Android sync time now
