### ISSUE TITLE
The Contentful framework fails to build in XCode Version 14.3.1

### ISSUE THREAD

**Issue by asaadjaber** [contentful/contentful.swift#386]
I experienced an issue building the Contentful framework in XCode Version 14.3.1 on MacOS 13.4.

When I built the Contentful.xcodeproj project in XCode with the platform destination set to iPhone 14 Pro, I got a build error. The error was in relation to the libarclite library in the XCode Toolchain. A file from the library was not found.

**Comment by jshier** [comment]
This is also #331.

**Comment by mariuskatcontentful** [comment]
I think its resolved. Any issues let me know
