### ISSUE TITLE
Privacy manifest updates

### ISSUE THREAD

**Issue by moaahmad** [contentful/contentful.swift#396]
Hello, we're currently updating our iOS app to adhere to Apple's new [privacy manifest requirements](https://developer.apple.com/news/?id=r1henawx) and were wondering if you have any plans to make the change in your iOS SDK?

If so, can you share your proposed timeline for the updates? We're conscious Apple have set a deadline for May 1st and want to ensure we're accurately informing our users of how we, and the 3rd party SDKs we use, use their data.

**Comment by mariuskatcontentful** [comment]
Hello, 

Will add it this week on all SDKs: Contentful, Persistence and RichTextRenderer

**Comment by stephengilroy-grx** [comment]
@mariuskatcontentful do we have a status update on this?

**Comment by mariuskatcontentful** [comment]
Have deployed an update

**Comment by mariuskatcontentful** [comment]
Closing as this is now resolved
