### ISSUE TITLE
Why other Contentful swift repositories are archived?

### ISSUE THREAD

**Issue by AMatecki** [contentful/contentful.swift#406]
Hey
Apologies for asking about other repositories, but I can't add new issues there. I wanted to integrate contentful-persistence.swift in my app, but I noticed it's marked as archived. Then I noticed all Swift repos from Contentful are also archived, besides this one. Is it a good idea to use contentful-persistence.swift now, or should I look for other solution?

Regards
Arek

**Comment by mariuskatcontentful** [comment]
Sorry, those repositories were archived by mistake and since been reverted a few days later after they were initially archived. Hope its all ok now
