### ISSUE TITLE
Neonichu Decodable Contains No Sources

### ISSUE THREAD

**Issue by oursevendev** [contentful/contentful.swift#5]
When running `swift build` there is a dependency hang-up; which results in no sources found in Decodable version: 0.3.3. Any insight to resolve this? Much appreciated!

Thanks.

**Comment by neonichu** [comment]
Which version of Swift are using to get this error? This library is still using Swift 2.2.

**Comment by oursevendev** [comment]
@neonichu I totally understand that SPM is still in beta until Swift 3~ release, I was under the impression I was also using Swift 2.2, however it looks like installing the SPM cli updated me to Swift 3.

<img width="1415" alt="swift-version" src="https://cloud.githubusercontent.com/assets/1783713/13753375/ea914e62-e9cf-11e5-8737-c0eb03875eff.png">

For this use of `contentful` however, it looks like it's missing the dependency of the `contentful` dependency.

**Comment by neonichu** [comment]
I'll make a Swift 3 branch to investigate this - I'm suspecting a change in swiftpm since 2.2 causes the issue as it still is able to access this dependency when using the 2.2 version of it.

**Comment by oursevendev** [comment]
@neonichu Thank you! No rush,:hourglass: however I'm looking forward to ditching CocoaPods & Carthage all together in favor of the `SwiftPackageManager` :smile:

Cheers! :beer:

**Comment by neonichu** [comment]
Sorry for taking some time to look at this, but there's #6 with Swift 3.0 support now. Alternatively, I recommend using `swift-2.2-SNAPSHOT-2015-12-22-a` with `master` — this also worked fine in my tests.
