### ISSUE TITLE
Initial sync returns empty entries if only one locale is present

### ISSUE THREAD

**Issue by abakhtin** [contentful/contentful.swift#62]
Hi, can you advise why I get empty field dictionary for unknown locale?
How can I get default locale translation? As I expect it should exist always for unknown locales. 

Thanks in anvance.
BR.

**Comment by loudmouth** [comment]
Hi there,


When using the Content Delivery API's [`/sync` endpoint](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/synchronization/initial-synchronization), all locales are always returned in the API response as a dictionary with the keys being the locale codes, and values being the corresponding localized field value. In the SDK, this dictionary of locale codes and localized values is stored in the `localizedFields` property for all `Resource` subclasses, including `Entry`. In addition to `localizedFields`, there is also `fields` dictionary, which will only show the values for the default locale of the space.

Does the above information help?

**Comment by abakhtin** [comment]
Thanks for promt reply
Yep you are right,
But you don't have access to localizedFields for entry class. We have only .fields property and I suppose it should return default locale values if it can not found fields for my current locale.
So when I'm on en-US and want to use data which is localized on server as en-GB what should I to do? 
The only possible way I see is to hardcode locale id to each entry: entry.locale = "en-GB" before accessing fields. Am I right?
I believe that it should be more convinient to have default locale on server side which whould be used for all unknown locales. Does it make sense?

**Comment by loudmouth** [comment]
The default locale for your space is indeed set server side. I'm having a bit of trouble understanding your comment here, so let's do what we can to clarify the situation and answer a few questions.
- What is the default locale of your space? Is it `en-GB`? There is always only one default locale of a space (see the [docs on locales for more info](https://www.contentful.com/developers/docs/concepts/locales/))
- I don't understand what you mean by "So when I'm on en-US". Could you elaborate?
- Which Contentful endpoint are you hitting? Is it `/entries`? If so, you can indeed specify the locale during the request. See how to do this [here](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/localization). Note that as mentioned above, the `/sync` endpoint always returns all locales and it is not possible to specify the locale when constructing the request.


A few additional notes:
- You are correct that after the entry has  should be able to switch locales by setting the `locale` property on your `Entry`.
- You are correct that `localizedFields` is a property internal to the SDK.

**Comment by loudmouth** [comment]
Hi @abakhtin there have been a few pull requests merged in the past few days that may have solved your problem. Can you give a test with the most recent commit on `master` and see if everything is working?

**Comment by loudmouth** [comment]
I'll be closing this ticket next week if there are no further comments. I believe #76 should have fixed the issue.

**Comment by abakhtin** [comment]
Hi @loudmouth, sorry for delay, I have no time to check updates right now. Will come back to it somewhere in future. Thanks for the update.

**Comment by loudmouth** [comment]
Sounds good. Thanks for the update, I'll leave it open until I hear some feedback ;-) Happy coding.

**Comment by abakhtin** [comment]
@loudmouth actually it would be better to close as I m not sure I will do it in nearest time. thanks again)

**Comment by loudmouth** [comment]
sure. I'll be here if you encounter future issues.
