### ISSUE TITLE
make setup_env does not install dependencies

### ISSUE THREAD

**Issue by sebastianludwig** [contentful/contentful.swift#69]
when I run `make setup_env` the binaries `carthage`, `swiftlint` etc are not installed. It's only checked if they need to be updated.

**Comment by loudmouth** [comment]
A PR to update the `Makefile` is more than welcome ;-) If you don't have capacity to contribute at the moment, just sit tight and I'll get a fix out soon.

In the meantime, use `brew` to install `carthage` and `swiftlint`

**Comment by loudmouth** [comment]
Actually, I shall take this one.
