### ISSUE TITLE
How to use entries() with linked entry IDs?

### ISSUE THREAD

**Issue by DavidNelsonAtMogo** [contentful/contentful.swift#77]
> - contentful.swift version number: 5.0
> - Xcode version number: 8.3.2
> - Target operating system(s) and version number(s)
    - [x] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [ ] Carthage
    - [x] Cocoapods

How do I use `client.fetchEntries()` with linked entries? I see in `Link.swift` the `Link` enum has a variable for it's resolved entry, but it is not publicly accessible. Also `includedEntries` in `ArrayResponse` is marked internal. So how do I access the linked entries?

**Comment by loudmouth** [comment]
Hi there,

The public API for `Link` exposes a few computed properties for convenient access to the linked [`Entry`](https://github.com/contentful/contentful.swift/blob/master/Sources/Link.swift#L64) or [`Asset`](https://github.com/contentful/contentful.swift/blob/master/Sources/Link.swift#L72).

So, as a practical example, the code for accessing a linked `Entry` at field named `"bestFriend"` would look like the following:

```
let bestFriend = (fields["bestFriend"] as? Link)?.entry
```

Please note that in the coming weeks there will be further iteration on what is currently called the `ContentModellable` protocol, and the plan is to add new variations of `fetchEntries` that will define your own model classes conforming to this protocol. The interface for accessing linked objects should improve as a result.

**Comment by DavidNelsonAtMogo** [comment]
Hey,

So the problem is that Link.entry is not set to public, it does not actually have a access control option set to it, which means it defaults to `internal`

**Comment by DavidNelsonAtMogo** [comment]
```
    /// The linked Entry, if it exists.
    var entry: Entry? {
        switch self {
        case .entry(let entry):     return entry
        default:                    return nil
        }
    }

    /// The linked Asset, if it exists.
    var asset: Asset? {
        switch self {
        case .asset(let asset):     return asset
        default:                    return nil
        }
    }
```

if these ^^ were set to public, that would solve the problem I believe. :)

**Comment by loudmouth** [comment]
@DavidNelsonAtMogo I'm offline until tomorrow CEST. Pull request is welcome if you're interested in contributing. otherwise, will fix this tomorrow.

**Comment by loudmouth** [comment]
@DavidNelsonAtMogo please point to the `master` branch in your dependency file. Will be publishing an official release in the coming days.
