### ISSUE TITLE
Link's not parsing correctly 

### ISSUE THREAD

**Issue by abakhtin** [contentful/contentful.swift#86]
> - contentful.swift version number: 0.6.0
> - Xcode version number: 8.3.2
> - Target operating system(s) and version number(s)
    - [x] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [x] Carthage
    - [ ] Cocoapods

Sometimes in fields for entry it contains row dictionary instead of link object for value:

Links for my object relationsships become:
"categories": <__NSArrayI 0x600000625960>(
{
    sys =     {
        id =12345;
        linkType = Entry;
        type = Link;
    };
} 
 
but in some cases it is valid link
"categories": [Contentful.Link.unresolved(Contentful.LinkSys(id: "12345", linkType: "Entry"))]

*12345 - is stub value

I'm not sure in which cases it appears but seems like a critical bug.

**Comment by loudmouth** [comment]
Hey @abakhtin is this only happening for `Link`s which represent one-to-many relationships? Can you perhaps share the code you are using to fetch entries from the API and how you are handling your callback?

**Comment by abakhtin** [comment]
client.initialSync { (result: Result<Contentful.SyncSpace>) in
                switch result {
                case let .success(syncSpace):
                    _ = syncSpace.entries.map { self.create(entry: $0) }
                    _ = syncSpace.assets.map { self.create(asset: $0) }
                    break
                default:
                    break
                }
                syncCompletion(result)
            }

    public func create(entry: Contentful.Entry) {
        print(entry.fields)
    }

A little bit simplified.

**Comment by abakhtin** [comment]
Seems like both one-to-many and one-to-one

**Comment by loudmouth** [comment]
@abakhtin a quick look at the code suggest that there might be an issue resolving links in the `initialSync` method. `initialSync` is the only place you have noticed this issue?

**Comment by abakhtin** [comment]
I do not tested update well. But we do not get this error before. We were on 0.4.0 and it works till today morning when we get error of parsing of our data.
After udate to 0.6.1 we passed it but get this new one.

**Comment by loudmouth** [comment]
Hey @abakhtin, after the last message, I'm a bit confused.

Is everything working as expected now?

If not, is there any chance you have reproduction steps? I have not encountered raw JSON in places where a `Link` should have been created yet.

**Comment by abakhtin** [comment]
Hi @loudmouth Sorry,

It is reproducing only in 0.6.1 (not 0.4.0)
Sorry, I can't help with steps right now. May be in some days.

**Comment by loudmouth** [comment]
I will do what I can to try and reproduce next week after I finish the current feature work I am working on.

In the meantime, if you do figure it out, reproduction steps would be extremely helpful.

**Comment by abakhtin** [comment]
Hi @loudmouth 
I get approve from my manager and can share some details.
So I get not parsed dictionary on initial sync with spaceId = it3h0h0p6zju

Here is example:
"categories": <__NSSingleObjectArrayI 0x60000000db30>(
{
    sys =     {
        id = 302E4OMh56UuGmqWKGkcmY;
        linkType = Entry;
        type = Link;
    };
}

Can you check it?

**Comment by loudmouth** [comment]
I can look into this first thing tomorrow morning. However, just having a space id will not help me reproduce the bug. If you'd like to share your credentials so that I can run tests against your space, i suggest opening a ticket at http://support.contentful.com/ as your `access_token` is necessary (and of course you should not be sharing your `access_token` in an open forum like Github).

If that is not something you are willing to do, then some other helpful pieces of information that you could share with me is:
1. Is the bug reproducible with the [newest version of the SDK](https://github.com/contentful/contentful.swift/releases/tag/0.7.0) (published earlier today)? Sync was refactored between 0.6.0 and 0.7.0
2. How many calls to `sync` are required to completely sync the entire space? If you can set breakpoints in the debugger at the methods `SyncSpace.sync` you should be able to find out how many times sync is called as the responses are paginated and take multiple requests to complete.

**Comment by abakhtin** [comment]
> (and of course you should not be sharing your access_token in an open forum like Github).
sure it's clear. I will provide details in support form if you need additional information
1. The problem is that I can not update to latest version now as we are prepared to release and it can add some new bugs and require additional workarounds.
2. Will check it tommorow.

**Comment by loudmouth** [comment]
When opening the ticket at support.contentful.com, feel free to tell the support engineer to forward the ticket to the iOS developer ;-)

You mentioned that 0.4.0 everything works properly? This will help me investigate.

**Comment by abakhtin** [comment]
Right about 0.4.0
Can you check please my another ticket(about deleted entries) as it is very urgent for us now?

**Comment by loudmouth** [comment]
Hi again @abakhtin. Thought I'd revisit this conversation as I know you've now had the chance to upgrade from `0.6.0` to `0.7.1`. Is this still an issue in the newest version?

**Comment by abakhtin** [comment]
I can not confirm that it is fixed because we change model structure. I can confirm only that we do not get into it now. I believe it can be closed till next reproducing.

**Comment by loudmouth** [comment]
Ok. I will close for now, but never hesitate to re-open if you see this again.
