### ISSUE TITLE
Deleted objects are not received sometimes.

### ISSUE THREAD

**Issue by abakhtin** [contentful/contentful.swift#88]
> - contentful.swift version number: 0.6.0
> - Xcode version number: 8.3
> - Target operating system(s) and version number(s)
    - [x] iOS: 
    - [ ] tvOS: 
    - [ ] watchOS:
    - [ ] macOS:
> - Package manager:
    - [x] Carthage
    - [ ] Cocoapods

I do not get callbacks about deleted objects sometimes and can not make local storage consistent. 
I use this code for syncing:
        if let syncToken = syncToken {
            let syncSpace = SyncSpace(client: client, syncToken: syncToken, delegate: self)
            syncSpace.sync(completion: syncCompletion)
        } else {
            client.initialSync { (result: Result<Contentful.SyncSpace>) in
                switch result { ... }
                syncCompletion(result)
            }
        }

My space id is "it3h0h0p6zju"
My sync token is "w5ZGw6JFwqZmVcKsE8Kow4grw45QdyYjw5Z6LSxvPsKBeCZqwq5lwrZNKxbDm8OEWhxVCsK9w5whJcOKIsOcwqHDqwJxaMKxb1XDhydRwqQgwrBKKA9PDDRxeV88UF0DPMKHDMKXw4xnBA"

Can you let me know some information from token? For example date of changes? And a list of changes I should receive for it?
I do not get callbacks about some deleted entries, but it works for most of them.

Thanks in advance.

**Comment by loudmouth** [comment]
Looking into it. Please add this information to the support ticket opened as corollary to #86

**Comment by loudmouth** [comment]
Are you using [contentful-persistence.swift](https://github.com/contentful/contentful-persistence.swift)? Or are you conforming to the `SyncSpaceDelegate` protocol yourself?

**Comment by abakhtin** [comment]
@loudmouth 
I implemented SyncSpaceDelegate myself.

contentful-persistence.swift was not working when I try it a month ago.

**Comment by loudmouth** [comment]
So you unpublish an `Entry` then try to refresh the local cache? Is there any chance you also re-publish before refreshing the local cache?

**Comment by loudmouth** [comment]
Curious if this is the same issue: https://github.com/contentful/contentful-persistence.objc/issues/18

**Comment by loudmouth** [comment]
I think it's possible that in `0.6.0` there is a bug in which delegate messages are not being sent at all for single page sync operations. In other words, if a sync operation is returning less than 10 items and therefore fits on one pages, the messages are not sent. If you `curl` your sync endpoint with the following command, how many items do you see? Is the key at the bottom `nextPageUrl` or `nextSyncUrl`?
```
curl "http://cdn.contentful.com/spaces/<YOUR_SPACE_ID>/sync?sync_token=<YOUR_SYNC_TOKEN>&access_token=<YOUR_ACCESS_TOKEN>
```

**Comment by abakhtin** [comment]
@loudmouth 
There two pages of data. I believe that second page deleted objects are not processed.
I sent this information in the ticket at support.contentful.com. You can check it now.
