### ISSUE TITLE
Segmentation fault: 11 on x86x64.swiftmodule

### ISSUE THREAD

**Issue by joshd567** [contentful/contentful.swift#9]
Artifact: Contentful.framework.zip
Version: 0.2.1

When attempting to run app that utilizes Contentful.framework  on iOS simulator the following error occurs.  **Note - Issue not present while running on device.**

3.	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAccessibility.h:248:12: loading members for 'UIAccessibilityAction'
4.	While type-checking expression at [<invalid loc> - <invalid loc>]
5.	While reading from ${ProjectDir}/Contentful.framework/Modules/Contentful.swiftmodule/x86_64.swiftmodule
6.	While deserializing extension of 'UInt' (ExtensionDecl #166)

**Comment by neonichu** [comment]
Could you please share a full stacktrace?

**Comment by neonichu** [comment]
Closing because of lack of feedback.
